(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.tree_trunk_foreground = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#330000").ss(3,1,1).p("Ai45iIFxAAMAAAAzFIlxAAg");
	this.shape.setTransform(0.025,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993300").s().p("Ai4ZjMAAAgzFIFxAAMAAAAzFg");
	this.shape_1.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tree_trunk_foreground, new cjs.Rectangle(-19.9,-164.9,39.9,329.9), null);


(lib.tree_trunk_background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#330000").ss(3,1,1).p("Ai45iIFxAAMAAAAzFIlxAAg");
	this.shape.setTransform(0.025,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#663300").s().p("Ai4ZjMAAAgzFIFxAAMAAAAzFg");
	this.shape_1.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tree_trunk_background, new cjs.Rectangle(-19.9,-164.9,39.9,329.9), null);


(lib.tree_leaves_foreground = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#006600").ss(3,1,1).p("AvrI+IkyACIMF1QIlQACINj30IN1XoIljACIAFAIQACAEACAEQGHKbGIKbIlkACIAGAKQABACABACQH0NUH0NVMg9hAAcQD0mwDymwIHftlQADAAACAAQACAAACAAIALAA");
	this.shape.setTransform(-24,75.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#009900").s().p("A3KWjIH0tlIAAAAIgMAAIgEAAIgFAAIkyACIMF1QIlQACINi30IN2XoIljADIAAAAIAFAIIAEAHIMOU2IljACIAAAAIAGAKIACAEIPoapMg9hAAcIHmtgg");
	this.shape_1.setTransform(-24,75.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tree_leaves_foreground, new cjs.Rectangle(-222.3,-156.6,396.70000000000005,464.4), null);


(lib.tree_leaves_far_background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#003300").s().p("A3KWjIH0tlIAAAAIgMAAIgEAAIgFAAIkyACIMF1QIlQACINi30IN2XoIljADIAFAIIAEAHIMOU2IljACIAGAKIACAEIN7XwIBtC5Mg9hAAcIHmtgg");
	this.shape.setTransform(-24,75.55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tree_leaves_far_background, new cjs.Rectangle(-220.8,-155.1,393.70000000000005,461.4), null);


(lib.tree_leaves_background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#003300").ss(3,1,1).p("AvrI+IkyACIMF1QIlQACINj30IN1XoIljACIAFAIQACAEACAEQGHKbGIKbIlkACIAGAKQABACABACQH0NUH0NVMg9hAAcQD0mwDymwIHftlQADAAACAAQACAAACAAIALAA");
	this.shape.setTransform(-24,75.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006600").s().p("A3KWjIH0tlIAAAAIgMAAIgEAAIgFAAIkyACIMF1QIlQACINi30IN2XoIljADIAAAAIAFAIIAEAHIMOU2IljACIAAAAIAGAKIACAEIPoapMg9hAAcIHmtgg");
	this.shape_1.setTransform(-24,75.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.tree_leaves_background, new cjs.Rectangle(-222.3,-156.6,396.70000000000005,464.4), null);


(lib.stairs = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(3,1,1).p("A1yNoIExAAIAAk8IExAAIAAkVIExAAIAAAVIAPAAIAAk7IExAAIAAkVIE/AAIAAk8IExAAIAAkUIExAAIAAAVIAPAAIAAk8IExAAIAAkVIExAAMAAAAthMgm0AAAIAAkYIkxAAg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("AxBWwIAAkYIkxAAIAAkxIExAAIAAk8IExAAIAAkUIExAAIAAAVIAPAAIAAk7IExAAIAAkVIE/AAIAAk7IExAAIAAkVIExAAIAAAVIAPAAIAAk8IExAAIAAkUIExAAMAAAAtfg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.stairs, new cjs.Rectangle(-141,-147.1,282,294.29999999999995), null);


(lib.sky = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#00BEFF","#ABE9FF","#FFFFFF"],[0,0.361,0.945],-300.5,0,300.5,0).s().p("Egu8AhSMAAAhCjMBd5AAAMAAABCjg");
	this.shape.setTransform(6.5,5.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.sky, new cjs.Rectangle(-294,-207.9,601,425.9), null);


(lib.paperPlane = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(4,1,1).p("AnTFKIAAD6ID0iaAmDFqIBOhIIVtvnAnTFKIBQAgIAsARIB4AvICkBAIHpDSAnTFKIpkjwMAhvgMfIpOWL");
	this.shape.setTransform(-106,70.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AGuK8InpjSIikhAIh5gvIB5AvIj0CaIAAj6IpkjwMAhvgMfI1tPnIhOBIIArARIAjhZIVtvnIpOWLgAmDFqIhQgggAQ4rFg");
	this.shape_1.setTransform(-106,70.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#000000").ss(4,1,1).p("ATQiTICZgYIiWgLMgo7gDAIAABzMAo4ABwI/LEtAzpDlIh/ATIAAn7AzpDlIBNBfQAmAsAAAHIF7jdg");
	this.shape_2.setTransform(-139.05,21.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AxSFEIhMhfIh+ATIAAn7MAo3ABwI/LEtInuBLIHuhLIl7DdQAAgHgngsgAUbiTMgo3gBwIAAhzMAo6ADAIgDAjgA0ckDg");
	this.shape_3.setTransform(-146.55,21.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},11).to({state:[{t:this.shape_3},{t:this.shape_2}]},6).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-279.5,-17.9,283.5,161.9);


(lib.leaf = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#009900").s().p("AhtCFQgJgHgEgRQgIgkAOglQAOgkAfgUQAVgOAEgGQAEgFAHgMQAGgJAIAAQADAEABAFIAGgCIAOgFQAKgCAFgDIAYgRQAOgKALABQgCgNAWgGIABgGQABgEACgEQAEgGAGgDQAHgCAHACQAHABAEAGQgIAFgJALIgCACQABAIgCAKIgIAZQgOApACAtIACAYQgBANgGAJQgEAGgLAIIgQAMIgMAOQgGAIgFAEQgKAIgSAFQgnALgoAAQgVAAgIgGgAA6hCQgZAQgUAJQgNAFgPAEIgJACIgIAJQgGAFgPAIQgPAIgGAFQgjAeAIBPQAiAAASgBQAdgDAVgIQAagKARgTQAUgVADgZQABgJgBgRQgCgSABgIQABgPAKgdIAFgPQgKAJgOAJg");
	this.shape.setTransform(-554.1571,148.0806);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00FF00").s().p("Ag/gJQAGgFAPgIQAPgJAGgFIAIgJIAJgBQAPgEANgGQAUgIAZgRQAOgJAKgJIgFAQQgKAcgBAPQgBAIACATQABAQgBAKQgDAYgUAVQgRATgaAKQgVAIgdADQgSACgigBQgIhPAjgdg");
	this.shape_1.setTransform(-555.2744,149.55);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#00FF00").s().p("AhYBeQgGhBAXgfQAQgRAOgIIAVgOQAMgJAFgBQAQgEALgEQAQgFASgKIAIgEIANgIIALgIIgDAOIAAABIgDAJQgFARgCAKIAAAEQgBAIABASQABAQgBAJIAAACQgDAQgJAPIgIAKIgCACQgJAJgMAHQgKAHgMAEIgMAFQgRAEgUABIgFAAIgNABIghgBg");
	this.shape_2.setTransform(-531.3216,174.2083);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#009900").s().p("AhNCFIgCAAQgUgBgHgGIgBAAQgIgHgEgQQgHgdAJgdIAEgOQAIgVANgOQALgMAMgJIAPgLIAJgJIAHgLIADgGQAHgJAIAAIAEAIIAFgDIACAAIAMgEIAJgDIAGgDIAQgJIAHgFQAOgJALABQgBgGAHgEQAFgDAIgCIABgFIADgGQADgEAEgCIADgCQAFgBAFABIAEAAQAGABAEAFIAAAAIgFAEIgHAHIgDAFIgBACIAAAAQABAIgDAKIgEAMIgEAMIgBADIgHAcIgCARQgCASABATIABAUIAAAEQgBALgEAIIgBACQgEAHgKAHIgPALIgCABIgGAHIgFAGIgBABQgGAHgFADQgIAGgOADIgFACQgkAJglAAIgEgBgABFhJIgNAHIgJAFQgRAKgQAFQgMAEgPADQgFACgMAJIgVAOQgOAIgRAQQgXAgAHBAIAuABIAFAAQATgCARgEIANgEQAMgEAKgHQAMgHAJgJIACgCIAHgKQAJgPADgQIAAgCQABgKAAgPQgCgTABgIIABgDQABgLAGgRIACgJIAAgBIAEgNIgLAIg");
	this.shape_3.setTransform(-530.2581,172.9513);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#00FF00").s().p("AgoBaIgugDQgGg/AXgfQARgQANgJQAOgIAHgGQAMgJAEgCIAagFQAQgDAQgHIAIgEQAHgCAFgDIAMgIIgCALIAAABIgBAIQgGAQgCALIAAADQgBAJAAARQABAPgCAJIAAADQgDAQgIAOIgGAKIgCABQgKAJgLAHQgKAHgMADIgNAEQgQADgTACIgFAAg");
	this.shape_4.setTransform(-507.3871,198.95);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#009900").s().p("AhLB/IgCAAQgTgBgIgGIAAAAQgJgIgEgPQgGgdAIgcIAFgOQAIgVANgNQAKgLAMgJIANgNIAJgJIAHgKIAEgGQAGgJAHAAQADADACADIAFgCIACgBQADgCAIgCIAJgDIAGgCIAQgJIAHgEQANgHALACQAAgGAGgDQAFgDAHgBIACgEIADgFIAGgFIADgBQAFgBAGACIADAAQAFABAFAEIAAABQgCAAgCACIgGAIIgDAFIAAACIgBAAQAAAIgCAKIgEALIgEAMIgBADIgGAbIgDARQgCARAAATIACAVIAAADQgBALgEAIIgBACQgEAHgJAHIgPALIgBABIgHAFIgFAGIgBACQgGAGgFACQgIAGgOACIgFABQgcAGgeAAIgRgBgABChGQgGADgHACIgIAEQgPAHgRADIgZAFQgFACgMAJQgGAGgPAIQgNAJgQAQQgXAfAGA/IAtADIAFAAQATgBARgEIAMgDQAMgEAKgHQAMgHAJgIIACgCIAHgJQAIgPADgQIAAgCQABgKAAgPQgBgRABgJIABgDQACgLAFgQIABgIIAAAAIACgMIgLAIg");
	this.shape_5.setTransform(-506.3408,197.8022);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#00FF00").s().p("AgnBVQgRgBgbgDQgGg/AXgeQAQgRANgIIAUgOIAQgLIAZgEQAQgBAOgFIAIgCQAHgBAFgDIALgHIAAAKIAAABIAAAGQgFAQgCAKIgBADQgBAJAAARIgBAYIAAACQgDAPgHAPIgHAKIgCABQgJAHgMAHQgKAHgMADIgMAEQgQADgTABIgFgBg");
	this.shape_6.setTransform(-483.4621,223.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#009900").s().p("AhIB6IgDgBQgTgBgHgGIgBgBQgIgHgEgPIAAAAQgGgcAIgdIAFgNQAIgUANgNIAUgUIANgNIAJgJIAHgKIADgHQAGgHAIgBIAEAFIAFgDIACgBQAEgCAHgDIAIgCIAGgCIAQgIIAHgDQANgGALADQAAgFAGgCQAEgCAHAAIACgDIADgEQADgDADgBIADgBIAKACIADAAQAFABAFADIAAABQAAAAgBAAQAAAAAAABQgBAAAAAAQgBABAAAAIgFAHIgCAGIgBACIAAAAQAAAHgDAKIgEALIgEAMIgBADIgGAaIgCARQgDARABATIABAUIAAADQgBALgDAIIgBACQgEAHgJAHIgOAKIgCABIgGAEIgGAGIgBACQgGAGgEACQgIAFgOABIgGABQgVADgXAAIgcgBgABAhEQgGADgGABIgIACQgOAFgQABIgZAEIgQALIgUAOQgNAIgQARQgXAeAGA/QAaADASABIAFABQASgBARgDIAMgEQAMgDAKgHQAMgHAJgHIACgBIAGgKQAHgPADgPIAAgCIACgYQgBgRACgJIAAgDQACgKAGgQIgBgGIAAgBIABgKIgLAHg");
	this.shape_7.setTransform(-482.4408,222.6813);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#00FF00").s().p("AgnBRQgRgCgagFQgGg9AXgeQAQgRAMgIIAUgPIAQgLIAXgBQAQABANgDIAHgBQAHABAFgDIALgGIABAIIAAAAIACAFQgGAPgCAKIAAADQgCAJAAAQIgCAYIAAACQgDAPgGAPQgDAGgDADIgCABIgVANQgKAHgMADIgMADIgiADIgFAAg");
	this.shape_8.setTransform(-459.3871,248.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#009900").s().p("AhGB0IgCgBQgTgCgHgGIgBgBQgIgHgEgOIAAgBQgGgbAIgcIAFgNQAIgTANgOIATgUIAMgNIAIgJIAHgKIAEgGQAGgIAHgBQADABABADIAGgEIABAAQAEgDAHgCIAIgDIAGgCIAQgGIAHgDQAMgEAKADQABgDAFgCIALAAIACgCIAEgCQACgDADgBIADAAIAKACIADAAQAEABAFADIAAAAIgCACIgEAHIgBAGIgBACIgBAAQAAAHgDAKIgEALIgEALIgBADQgBAMgEAOIgDARQgCARAAASIABAUIAAADQAAALgDAHIgBACQgEAIgIAGIgPAKIgBABIgHADIgFAGIgBACQgGAFgFABQgHAFgOAAIgGABIgdABQgUAAgWgCgAgKg7IgPALIgUAOQgNAIgPASQgXAdAGA9QAZAFARACIAFABIAjgDIAMgEQAMgDAKgGIAUgNIACgBQAEgEADgFQAGgQADgPIAAgCIABgXQAAgQACgJIABgDQACgLAFgPIgBgEIAAgBIgBgIIgLAGQgGADgGAAIgIABQgMACgQgBIgYACg");
	this.shape_9.setTransform(-458.5408,247.5893);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#00FF00").s().p("AgnBMIgqgJQgFg8AXgdQAPgRAMgIIAUgPQALgJAEgCIAWAAQAQAEALgBIAHABQAGABAFgCIAMgGIACAHIAAAAIADADQgFAPgDAKIAAACQgDAKAAAPIgCAXIAAACQgDAOgFAQIgGAJIgCABIgVAMQgJAGgMADIgMADQgQACgSAAIgFgBg");
	this.shape_10.setTransform(-435.3031,273.15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#009900").s().p("AAHBxIgFAAQggABglgFIgDgBQgSgCgIgGIAAgBQgIgHgEgOIAAgBQgGgbAIgbIAFgNQAIgTANgNIASgUIALgOIAIgJIAHgKIAEgGQAFgHAHgCIAFADIAFgDIACgBIAKgFIAHgDIAGgCQAEAAAMgFIAHgCQAMgCAKADQABgCAFgBIAKABIACAAIAEgBQACgCADgBIADAAIAJADQABAAAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAEAAAFADIAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAABAAAAIgDAHIgBAGIAAACIgBAAIgEARIgDAKIgFALIgBADQAAALgEAPIgDAQQgDAQABASIAAAUIABADQgBALgDAHIAAACQgEAIgIAGIgOAKIgCABIgGACIgGAFIgBACQgGAFgEABQgGAEgLAAIgFgBgAgXg4IgUAPQgMAIgPARQgXAdAFA9IAqAJIAFAAQASAAAQgCIAMgDQAMgDAJgGIAVgMIACgBIAGgJQAFgPADgPIAAgCIACgXQAAgPADgJIAAgDQADgKAFgPIgDgDIAAAAIgCgHIgMAGQgFACgGgBIgHgBQgLABgQgDIgWgBQgEACgLAJg");
	this.shape_11.setTransform(-434.6408,272.5091);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#00FF00").s().p("AgnBMQgRgEgYgIQgGg6AYgdQAPgRALgIQANgJAHgHIAOgLIAVADIAZAHIAHACQAGACAFgCIAMgFIAEAFIAAAAIAEACIgJAYIAAACIgDAYIgDAWIAAAEIgHAdQgCAGgDACIgCABIgVALQgJAGgMACIgMADIghABIgFAAg");
	this.shape_12.setTransform(-411.236,297.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#009900").s().p("AAIBwIgFAAQgfgBgkgHIgEgBQgSgDgHgGIgBgBQgIgHgDgOIAAgBQgGgZAJgcIAEgMQAIgTAMgMQALgLAHgJIAKgOIAIgKIAHgJIAEgGQAFgHAGgCIAFABIAFgEIACAAQAEgEAGgCIAHgCIAGgCIAPgEIAHgBQAMgCAJAFQACgBAEgBIAKAEIACAAIAEAAIAFgCIADABIAJADIACAAQAFAAAEADIABAAQgBAAAAABIgCAHIAAAGIAAACIgBABIgFAPIgDALIgEALIgCACQABALgFAPIgCAQQgDAQAAASIABATIAAADQAAAKgDAHIgBADQgDAHgIAHIgOAJIgBABIgHABIgFAFIgBACQgGAEgFAAQgGADgIAAIgHAAgAgVg+QgHAGgNAJQgLAIgPASQgYAcAGA7QAYAIARAEIAFAAIAhgBIAMgDQAMgCAJgGIAVgLIACgBQADgDACgFIAHgeIAAgDIADgWIADgYIAAgCIAJgYIgEgCIAAgBIgEgEIgMAFQgFACgGgDIgHgBIgZgHIgVgDIgOALg");
	this.shape_13.setTransform(-410.708,297.3169);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#00FF00").s().p("AgiBMIgFAAQgRgFgXgIQgFg7AXgcQAPgRAKgIQANgJAHgHIAOgLIAUAFIAXALIAGADQAGAEAFgBIAMgFIAGADIAAAAIAFABIgJAXIAAACQgDAKgBANIgDAWIAAADIgGAdQgCAGgDACIgCABIgVAKQgJAGgMACIgLACIgWABIgLgBg");
	this.shape_14.setTransform(-387.1522,321.7583);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#009900").s().p("AAIBwIgFAAQgegDgjgIIgEgBQgRgEgIgGIAAAAQgIgIgEgNIAAgBQgFgZAIgbIAEgNQAIgSANgMQALgKAGgJIAJgPIAHgKIAHgJIAEgGQAFgHAGgCIAFAAIAFgEIACgBQAEgDAFgCIAHgDIAGgBQAEAAALgDIAHAAQAMgBAIAGIAGAAIAJAFIADABIAEABIAEAAIADABIAJAEQAAAAABgBQAAAAAAAAQAAAAABAAQAAAAAAAAQAEAAAFADQAAAAAAgBQAAAAAAAAQAAAAAAAAQABABAAAAIgBAHIAAAGIAAADIgBAAIgFAPIgDAKIgFALIgBADQACAKgFAPIgDAPQgDAQAAASIAAASIABAEQAAAKgDAHIAAACQgDAIgIAGQgHAGgHAEIgBAAQgEABgDgBIgFAFIgBABQgGAEgFAAQgEACgHAAIgKgBgAgUhCQgHAHgNAJQgKAIgPARQgXAcAFA6QAXAJARAFIAFAAQARAAAQgBIALgBQAMgDAJgFIAVgKIACgBQADgDACgFIAGgdIAAgDIADgWQABgOADgKIAAgBIAJgYIgFAAIAAgBIgGgCIgMAFQgFABgGgEIgGgDIgXgLIgUgFIgOALg");
	this.shape_15.setTransform(-386.7768,321.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#00FF00").s().p("AgjBNIgEAAQgRgGgWgKQgFg5AXgcQAPgRAJgIQANgJAHgHIAOgLIASAHQAQAJAGAGIAFAEQAGAGAFgBIAMgEIAHAAIAAABIAHgBIgJAWIgBACQgDAKgBANIgDAVIgBADIgFAdQgBAGgDACIgDAAIgUAJQgJAGgMACIgLABIghAAg");
	this.shape_16.setTransform(-363.0772,346.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#009900").s().p("AAHBxIgEgBQgdgFgjgJIgDgBQgSgEgHgGIgBgBQgHgIgEgMIAAgBQgFgZAIgaIAEgNQAIgSANgLQALgKAFgJIAIgQIAGgKIAHgJIAFgFQAFgHAFgDIAGgBIAFgEIABgBQAEgDAFgCIAHgDIAGgBIAPgCIAGABQAMABAIAGIAGACIAIAGIADACIAEADIAEAAIADACIAJAFIACgBQADAAAFACQAAAAABAAQAAgBAAAAQAAAAAAAAQABAAAAAAQABABgBAGIAAAHIABADIgBAAIgGAPIgDAJIgEALIgCADQADAJgGAPIgCAPQgEAQAAARIABATIAAADQAAAKgCAHIgBACQgCAIgHAGQgHAGgHADIgBABQgEAAgDgCIgFAFIgBACQgHADgFgBQgDACgFAAIgNgCgAgThGQgHAHgNAJQgJAIgPASQgXAcAFA4QAWAKARAGIAEAAIAhABIALgCQAMgCAJgFIAUgJIADgBQADgCABgFIAFgdIABgDIADgWQABgMADgLIABgBIAJgXIgHABIAAAAIgHgBIgMAEQgFABgGgFIgFgEQgGgHgQgJIgSgHIgOALg");
	this.shape_17.setTransform(-362.783,346.4625);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#00FF00").s().p("AgjBNIgEgBQgRgGgUgLQgGg4AYgcQAOgRAJgIIATgQIANgLIASAIQAQALAEAJIAFAGQAGAGAFAAIALgEIAJgBIAAABIAIgDIgJAWIgBABQgDALgCALIgDAWIgBADIgEAcQgBAGgDACIgDAAQgIACgMAGQgJAFgMACIgKABIghgBg");
	this.shape_18.setTransform(-339.0022,370.325);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#009900").s().p("AAHByIgEgBIg+gRIgEgCQgRgEgHgGIgBgBQgHgIgEgMIAAgBQgFgYAIgbIAEgLQAIgSANgLQALgKADgJIAIgQIAGgKIAHgJIAEgGIALgJIAFgCIAFgFIABgBIAKgGIAFgCIAGgBIAPgBIAHACQALACAIAHIAGAEQADAEAEAEIADADIAEAEIAEABIADACQAEAEAEACIACgBIAIABQAAAAAAAAQABgBAAAAQAAAAABAAQAAAAABAAQABABAAAGIABAHIAAADIgBAAIgGAOIgDAJIgEALIgCADQAEAJgGAOQAAAEgDALQgDAQAAARIAAASIAAAEQAAAJgBAHIgBACQgCAIgHAGQgGAFgHAEIgCAAQgEABgCgEIgGAGIgBABQgGADgFgBIgGABQgGAAgJgDgAgShJIgTAQQgKAIgOARQgXAdAFA3QAUALARAGIAFABIAgABIALgBQAMgCAJgFQAMgGAIgCIACAAQADgCACgGIAEgcIAAgDIAEgVQABgMAEgLIAAgBIAJgWIgIADIAAgBIgIABIgMAEQgFAAgFgGIgGgGQgEgJgPgLIgSgIIgNALg");
	this.shape_19.setTransform(-338.758,371.0313);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#00FF00").s().p("AgjBNIgEAAQgRgIgUgMQgFg3AYgbQAOgRAIgIQAMgJAHgIIANgLQAJAFAHAGQAQANACALIAFAHQAGAIAEAAIAMgDIAKgDIAKgEIgKAVIAAABIgGAVIgEAWIgBADQgCAMgBAQQgBAGgCABIgDAAQgIACgMAFQgJAFgMACIgKAAIgggCg");
	this.shape_20.setTransform(-314.9189,394.575);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#009900").s().p("AAGBzIgEgCIg8gUIgEgCQgRgFgHgGIgBAAQgHgIgEgMIAAgBQgFgYAJgaIAEgKQAIgTAMgKQALgKADgJIAGgRIAGgKIAHgIIAFgGIAJgJIAGgEIAFgEIABgBQAEgFAFgCIAFgCIAGgBIAPAAIAGADQALAEAIAHIAGAGIAGAJIAEAFIAEAFIADACIADADIAJAGQAAgBAAAAQAAAAAAAAQAAAAABgBQAAAAAAAAIAIABIAAABQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAAAQADAAAAAGIABAIIABACIgBABQgDADgEALIgDAIQgCAHgCAEIgCACQAEAJgGAOIgCAPQgEAPgBARIABASIAAAEQAAAJgBAGIgBADQgCAIgGAGQgGAFgHAEIgBAAQgFAAgCgEIgGAFIgBABQgGACgFgBIgFABQgGAAgKgEgAgShNQgHAIgMAJQgIAIgOARQgYAcAFA2QAUAMARAIIAEAAIAgACIAKAAQAMgCAJgFQAMgFAIgCIADAAQACgBABgGQABgQACgMIABgDIAEgVIAGgWIAAgBIAKgVIgKAEIgKADIgMADQgEAAgGgIIgFgHQgCgLgQgNQgHgGgJgFIgNALg");
	this.shape_21.setTransform(-314.7176,395.5641);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#00FF00").s().p("AgEBQIgkgDQgRgJgSgNQgFg2AYgbQAIgNAQgPIAcgZQAfAWABATQAIARAGABQALgBANgGIAKgGIgJAVQgKAYgCAVQgDAMABAQQgBAGgDABQgIAAgOAGQgLAGgRAAIgDAAg");
	this.shape_22.setTransform(-290.8439,418.8767);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#009900").s().p("AAaB5QgHACgOgHQgcgNgmgOQgRgFgHgGQgIgJgDgNQgFgXAIgZQAJgaAQgNQALgJABgJQACgIAEgKQAEgLAIgHQALgPAPgLQAIgIAFgBQAHgBAOACQAUAJAKAPQAJARAIAJQAFAHAGADQgBgDAKACQAAgBABAAQAAgBAAAAQABAAABAAQAAAAABAAQADAAAAAGIADALQgFADgHATQgCAIgEAFQAGAIgHAOQABADgDAMQgGAXABAaQACAMgCAHQgBAKgHAGQgFAFgIAEQgGAAgCgFIgHAGIgGABIgFgBgAghhCQgRAPgIANQgXAcAFA1QASANARAJIAjADQATABAMgHQAPgGAIAAQACgBABgGQAAgQACgMQADgVAJgYIAKgVIgLAGQgNAGgKABQgGgBgJgRQAAgTgfgWIgcAZg");
	this.shape_23.setTransform(-290.6926,420.0969);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#00FF00").s().p("AgFBRIgLgCIgVgDIgDgBQgRgJgQgPQgCgXAEgTQAEgXANgPQAJgOARgQIAcgVQAfAWAAAVQAKARADABQAOgCAHgCIAFgCIAFgCIgCAFIgEAIIgEAIIgFAOQgFAQgCAQIgCAJIgBATIgBAFQAAAAAAAAQAAABgBAAQAAAAAAAAQgBABAAAAIgHAAQgGAAgJADQgIADgMAAIgFAAIgFAAg");
	this.shape_24.setTransform(-266.7833,425.6375);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#009900").s().p("AAwB9QgEgBgCgEQgCAAgDAEIgEABIgCgBIgFgBQgEABgEgCQgFgBgIgEIgFgDQgagOghgOIgJgDQgKgFgFgEIgEgFQgFgHgDgJQgBgIAAgJIABgTIADgOIAFgNQAGgNAJgJIAEgFQALgJACgKQACgIAEgJQAEgJAGgGIAEgDQAHgKAIgHIALgIIAHgEQADgDADAAQAIgBANADQAPAIAKAMIAFAGQAIARAIAKQAEAGAGAEQgBgCAHACIACAAQAAAAAAgBQABAAAAAAQABgBAAAAQABAAAAABQADAAAAAGIADALIgCABQgDADgDANIgDAGIgCAGIgEAGIABACIABAFQAAAEgDAJIgBACIgCAKIgBAFIgDARQgCAMAAANIABAIQAAAHgBAGIAAAEIAAACIAAAEQgCAGgEAFIgBACQgDADgFADIgGADIgCAAgAgehJQgQAQgKAOQgMAPgEAYQgFASACAXQARAPAQAJIADABIAWADIALACIAKAAQAMAAAIgDQAJgDAGAAIAHAAQAAAAAAgBQABAAAAAAQAAAAAAgBQABAAAAAAIABgFIABgTIABgJQADgQAEgPIAGgPIAEgIIAEgIIACgFIgFACIgFACQgHACgOACQgEgBgJgRQgBgVgegWIgdAVg");
	this.shape_25.setTransform(-266.65,427.0464);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#00FF00").s().p("AgGBRIgKgCIgWgFIgDAAQgQgLgPgPQgCgYAFgUQAFgWANgQQAJgOARgQIAcgSQAfAYABAVQAJARADABQAMABAGgBIAFgCIAEgBIgCAFIgEAIIgEAIIgGAPQgFAQgCAQIgCAKQgBAJAAAKIgBAFQAAAAAAAAQgBABAAAAQAAAAgBAAQAAAAAAAAIgHgBQgGgBgIACQgJACgLAAIgKgCg");
	this.shape_26.setTransform(-242.7187,432.425);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#009900").s().p("AAuCAQgEgBgBgEIgGADIgDABIgBgBIgGgBIgIgCQgFgCgHgEIgFgEQgZgPghgQIgJgEQgJgEgFgEIgFgGQgFgHgCgJIgBgBQgBgHAAgKIACgSIADgNIAEgPQAFgNAJgKIAFgEQAKgLADgJQACgIAEgJQAEgJAHgHIADgDQAIgJAIgHIALgHIAHgDQAEgCAEAAQAHAAANADQAPAIAJAMIAFAHQAIASAHAKQAEAGAFAFQAAgBAGACIABAAQABAAAAAAQAAAAABgBQAAAAAAAAQABAAAAAAQADACAAAFIACALIgBAAQgDAFgDAMIgCAHIgCAGQgCADgDACIABABQABADAAACQAAAFgEAIIgBADIgBAKIgCAFIgDARIgDAZIABAJQABAHgCAHIAAADIABACIgBAFQAAAGgEAFIgCABQgDAEgEADIgHACIgCAAgAgbhQQgQAPgKAOQgNAQgFAXQgEATABAYQAPAPARALIADAAIAVAGIALABIAKACQALAAAIgCQAIgCAHACIAGAAQABAAAAAAQAAAAABAAQAAAAAAAAQABgBAAAAIABgFQgBgKACgJIABgKQACgQAGgPIAGgQIAEgIIADgIIACgFIgEABIgEACQgHABgMAAQgDgCgIgRQgBgVgfgXIgdASg");
	this.shape_27.setTransform(-242.575,434.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#00FF00").s().p("AAkBUQgGgCgIABIgTgBIgKgCIgKgDIgVgGIgDgBQgQgLgOgRQgCgYAGgTQAFgXAOgRQAJgOARgQIAdgOQAfAYABAWQAIARACADQAKACAGAAIAEgBIAEgBIgCAGIgEAIIgEAHIgGAQQgGAQgCAQIgCAKQgBAKAAAKIgBAFIgCABIgHgCg");
	this.shape_28.setTransform(-218.6517,439.375);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#009900").s().p("AArCEQgDgBgBgEIgFABIgCAAIgCgBIgGgCQgDAAgEgCQgFgBgHgGIgFgEQgYgRgggRIgJgEQgJgFgFgEIgFgFQgGgHgCgKIAAAAQgCgIABgKIABgTIADgNQABgJADgGQAFgNAJgLIAEgEQAKgLAEgKIAHgQQAEgJAHgHIADgDQAIgKAIgGIAMgGQAEgCADgBQAEgBAEAAQAHABANAEQAPAJAJANIAEAHIAPAcQAEAHAEAEIAFADIABAAQAAAAAAAAQABAAAAAAQAAAAABAAQAAAAABAAQACACAAAGIACAKIgBABQgCAEgDANIgCAGIgCAHQgCADgDABIAAABQABACAAADQAAAEgEAJIgBADIgCAKIgCAGIgDARIgEAZQACAEAAAFQAAAHgBAHIAAAEIAAACIAAAEQAAAGgEAFIgCACQgCAEgFADIgHADIgDgBgAAjBCIAGACIACgBIABgFQAAgKACgKIABgKQADgQAFgQIAGgPIAEgIIAEgIIACgGIgEABIgEABQgFAAgKgCQgDgDgIgRQgBgWgegYIgdAOQgRAQgKAOQgNARgGAXQgFATACAYQANARAQALIADABIAVAGIALADIAKACIATABIADAAIALABg");
	this.shape_29.setTransform(-218.5062,441.1688);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#00FF00").s().p("AAoBZIgGgCQgGgDgIAAIgSgDIgKgDIgKgEIgVgIIgDAAQgPgMgNgSQgBgZAGgTQAGgXAOgSQAJgNASgQIAdgLQAeAZABAWIAJAVQAJAFAFAAIADAAIADAAIgBAFIgEAIIgFAIIgGAPQgGARgCARIgCAKIgCAUIAAAFIgBABIgCgBg");
	this.shape_30.setTransform(-194.615,446.4125);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#009900").s().p("AApCJQgCgCgBgEQgBAAAAAAQAAAAgBAAQgBAAAAAAQgBAAgBAAIgCgBIgBAAIgGgDIgHgDQgFgBgHgHIgFgEQgXgTgggSIgJgFIgOgJIgFgFQgFgIgDgJIAAgBQgCgIABgKIACgSIACgPQABgIADgGQAEgOAJgLIAEgFQAKgKAEgKIAIgRQAFgJAGgHIAEgDQAJgKAIgGQAGgDAGgBQADgCAEAAIAIgBQAIACAMAEQAOAKAJAOIAFAHIANAdQAEAHAEAFIAEADIABABIACABQACABAAAGIABALIAAABQgCAEgCANIgCAHIgCAGQgDADgDABIAAAAQABACAAADQAAAFgEAJIgCADIgCAJIgBAHIgEASIgEAYQABAEAAAFQABAHgCAHIABAFIAAACIAAAEQAAAGgEAGIgBABQgDAEgFADIgHADIgDAAgAgUhgQgRAQgKAOQgOARgGAXQgGAVACAXQAMASAQAMIADABIAVAIIAKAEIAKACIASADQAHAAAGADIAHADIACAAIABgFIACgVIABgKQADgRAGgQIAGgPIAEgIIAEgIIACgGIgEAAIgDAAQgFAAgIgFIgJgUQgBgWgfgZIgdAKg");
	this.shape_31.setTransform(-194.4667,448.1917);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#00FF00").s().p("AAmBdIgHgEQgGgDgHgCIgRgEIgKgEIgKgEIgVgKIgDgBQgPgMgLgUQgBgYAGgUQAHgXAOgSQAKgOARgQQASgFAMgCQAeAaACAXIAHAVQAHAHAEABIADAAIADABIgCAGIgEAIIgEAHIgHAQQgGARgDARIgBALQgCAKAAAKIgBAFIgBABIgBgBg");
	this.shape_32.setTransform(-170.5391,453.4625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#009900").s().p("AAnCNQgCgCgBgEIgEgCIgCgBIgBgBIgGgCIgHgEQgEgCgHgHIgFgFQgWgVgfgTIgJgFQgJgFgFgEIgFgFQgGgIgCgJIgBgBQgBgIABgLIACgSIABgPQABgJADgGQADgNAKgMIAEgFQAJgLAFgLIAIgQQAFgJAHgHIAEgDQAJgKAIgFQAGgDAGgBQAEgCAEABQAEgBAEABQAIACAMAFQAOALAJAOIAEAHIANAfIAGAMQAAABAEADIABABIABACQACACAAAGIABALIgBAAQgBAEgBANIgCAIIgDAGIgFACIAAABIAAAFQAAAEgFAKIgBADIgDAKIgBAGIgEASQgCAOgDALQACAEAAAFQABAHgDAIIABAEIABADIAAAEQAAAGgDAFIgCACQgDAEgFADIgHADIgDAAgAgRhoQgRARgKANQgOASgHAXQgGAVABAYQALATAPANIADABIAVAJIAKAEIAKAEIARAFQAHABAGAEIAHAEIACAAIABgFQAAgLACgKIABgKQADgSAGgQIAHgPIAEgJIAEgHIACgGIgDgBIgDgBQgEgBgHgHIgHgVQgCgXgegZQgMABgSAFg");
	this.shape_33.setTransform(-170.42,455.2167);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#00FF00").s().p("AAjBhIgGgFQgFgEgHgDIgRgHIgKgEIgKgFIgUgLIgDgBQgPgOgJgUQgCgYAHgVQAHgXAPgTQAKgNASgRQASgDAMABQAeAaABAXIAGAWQAFAJAEACIACABIACACIgBAGIgEAGIgFAJIgGAQQgGARgDASIgCAKIgDAVIAAAGIgDgBg");
	this.shape_34.setTransform(-146.4882,460.5389);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#009900").s().p("AAlCSQgCgCgBgFQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBAAgBgBIgCgBIgBgBIgGgDIgHgFQgEgCgGgIIgFgFQgVgXgfgUIgJgGQgJgFgEgEIgGgFQgGgIgCgJIgBgBQgBgIABgLIACgSIABgQQABgJACgGQADgOAKgMIAEgGQAJgLAFgKIAJgQQAFgJAIgIIADgDQAKgKAIgFQAGgCAGgBIAJAAIAIABQAIADALAGQAOALAJAPIAEAHQAIASAEAOIAGAMQgBACADAEIABABIABACIABAIIABAMIAAAAQgCAFAAANIgBAHQgBAEgCACIgGACIAAAAIAAAGQgBAEgFAKIgBADIgDAKIgBAGIgEATQgCAOgEALQADAEAAAFQAAAHgDAIIABAEIABADIAAAEQABAGgEAGIgBABQgDAFgFADQgEACgEABIgCAAgAgOhvQgRARgKANQgPATgHAXQgHAVABAYQAJAUAQAOIACABIAVALIAKAFIAKAEIAQAHQAHADAGAEIAGAFIACABIABgGIACgVIACgKQADgSAGgRIAHgPIAFgJIAEgHIABgGIgDgCIgCgBQgDgCgFgJIgGgWQgCgXgdgaIgGAAQgKAAgPACg");
	this.shape_35.setTransform(-146.345,462.2125);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#00FF00").s().p("AAhBlIgFgFQgGgGgGgDQgIgGgIgDIgKgFIgKgGIgVgMIgCgBQgPgPgIgVQgBgYAIgXQAHgWAQgTQAKgNASgSQATgCAMAEQAdAaABAZIAFAWQADALADADIABACIACACIAAAGIgFAHIgFAJIgHAQQgGAQgDAUIgCAKIgDAVIAAAGIgDgCg");
	this.shape_36.setTransform(-122.4618,467.4886);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#009900").s().p("AAiCXIgBgHQgBgDgCgBIgBgCIgCgCQgDgBgCgCIgHgFQgEgDgHgIIgEgGQgUgZgfgVIgIgGIgOgJIgFgGQgGgIgDgJIAAgBQgCgIABgLIACgTIABgQQAAgJACgGQAEgOAJgMIAEgHQAJgLAGgLIAJgQQAGgIAHgIIAEgDQAKgLAIgEQAHgCAGAAIAJABIAIACIATAKQAOALAIAQIAEAIQAIASAEAPIAEAMQAAACACAEIABACIABADIAAAIQAAAHABAFIgBAAQgBAFABANIgBAIQgBADgCADIgGABIgBAAIAAAGQgBADgFALIgCADIgDAKIgBAHIgEATQgCAOgFAKQADAEAAAGQAAAHgDAIIACAEIABADIAAAEQABAHgEAGIgBABQgCAFgGADQgEACgEABIgDAAgAgKh2QgSASgKANQgQATgHAWQgIAXABAYQAIAVAPAPIACABIAVAMIAKAGIAKAFQAIADAIAGQAGADAGAGIAFAFIADACIAAgGIADgVIACgKQADgUAGgQIAHgPIAFgJIAFgIIAAgGIgCgCIgBgCQgDgDgDgLIgFgWQgBgZgdgaQgIgCgLAAIgMAAg");
	this.shape_37.setTransform(-122.295,469.1708);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#00FF00").s().p("AAfBrIgGgHIgLgLQgIgHgHgEIgKgGIgLgGIgUgOIgCgBQgPgQgGgWQgBgYAIgXQAIgWAQgUQAKgNASgSQAUAAAMAFQAdAbACAaQADAQAAAGQABAOACAEIABACIACADIgBAGIgEAHIgFAJIgIARQgGAQgDAUIgCAKQgDALAAALIgBAFIgCgBg");
	this.shape_38.setTransform(-98.3862,474.375);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#009900").s().p("AAgCcIgBgHIgCgGIgBgCIgBgCQgDgBgDgDIgHgGQgDgCgHgKIgEgFQgTgbgegXIgJgGQgIgFgFgFIgFgFQgHgIgCgKIgBgBQgBgIABgLIACgTIAAgQQAAgKACgGQADgNAJgOIAFgGIAPgXIAJgQQAGgIAIgIIAEgDQAKgLAJgDQAFgDAIABIAJACIAIADIATALQANAMAJAQIAEAIQAIASADAQIADANQgBADACAEIABACIAAAEIAAAJIAAALIAAAAQgBAGACANIgBAHQgBAEgDADIgGAAIgBAAIAAAGQgBADgGALIgBADIgEAKIgBAHIgEATQgCAPgGAKQAEAEAAAGQAAAHgEAJIACAEIABADIABAEQABAHgDAFIgBACQgDAFgGADQgEACgEABIgDAAgAgjheQgRAUgHAWQgJAXACAZQAGAWAPAPIACACIAUANIAKAGIAKAHQAHAEAIAHIAMAKIAFAHIACACIABgGQABgKACgLIACgLQAEgUAGgQIAHgQIAFgJIAFgHIAAgGIgBgDIgCgDQgBgEgCgNQAAgGgDgRQgCgZgcgbQgMgGgUAAQgSASgKANg");
	this.shape_39.setTransform(-98.225,476.1107);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#00FF00").s().p("AAdBwIgGgIQgFgHgGgFQgIgJgGgFIgKgHIgKgHIgUgPIgCgBQgPgQgFgYQgBgYAJgYQAIgWARgUQAKgNATgSQAUABAMAIQAcAcACAaQADAQgBAHQAAAQABAEIAAAEIACADIgBAGIgEAHIgGAKIgHAQQgHAQgDAVIgCAKIgEAXIAAAFIgCgCg");
	this.shape_40.setTransform(-74.33,481.275);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#009900").s().p("AAdChIAAgHIgCgIIgBgCIgBgCIgFgEIgHgHQgDgDgHgKIgDgGQgTgdgegXIgIgHIgNgKIgGgFQgGgJgDgJIgBgCQgBgIACgKIACgUIAAgRQgBgKACgGQACgNAKgOIAEgHIAQgXIAKgQIAOgQIAEgEQALgKAIgDQAGgCAIACIAJACIAIAEQAJAFAKAHQANANAIARIAEAIQAIASACARIADANIAAAIIAAACIAAAFIAAAJIAAAMIACASIgBAIQgBAEgDADIgGAAIgCgBIAAAGQgBADgGALIgCAEIgDAJIgCAIIgEATQgCAQgGAJQAEAEAAAGQAAAHgEAJIACAEIABAEIABAEQABAHgDAFIgBACQgCAFgGADQgEADgFAAIgDAAgAghhkQgRAUgIAWQgJAYABAZQAFAXAOAQIACABIAUAPIAKAHIAKAHQAHAFAIAJQAFAFAGAHIAFAIIACACIABgFIADgXIACgKQAEgVAGgQIAIgQIAFgJIAFgHIAAgHIgBgDIgBgEQgBgEABgQQAAgHgCgQQgCgagcgcQgMgIgVgBQgSASgKANg");
	this.shape_41.setTransform(-74.095,483.075);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#00FF00").s().p("AAaB1IgGgIQgFgIgFgGQgIgLgGgFIgKgIIgKgIIgTgQIgCgCQgOgRgEgZQgBgYAKgYQAIgWASgVQAKgNASgSQAVADAMAKQAcAcACAbQACAQgBAIIgCAXIAAAEIABAEIAAAGIgFAIIgGAKIgHAQQgHAQgEAVIgCALIgEAXIAAAFIgCgDg");
	this.shape_42.setTransform(-50.2148,488.125);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#009900").s().p("AAaCmIABgHIgBgJIgBgDIgBgCIgFgFIgHgHQgDgDgGgLIgDgGQgSgfgegZIgIgHIgNgKIgGgFQgGgJgDgJIgBgCQgBgIACgLQACgPAAgFIgBgRQgBgKACgHQACgNAKgOIAEgHIAQgYIAKgPIAPgRIAEgDQAMgLAIgDQAGgBAIACIAJADIAJAFQAJAGAJAIQANANAIASIAEAIQAIASABASIACANIAAAKIAAABIgBAGIgBAKIAAALIAAABIADARQAAAFgBAEQgBAFgCACIgHgBIgCAAIgBAFIgHAOIgCAEIgEAKIgBAIIgEAUQgCAPgHAJQAEAEAAAHQAAAHgFAJIADAEIABAEIABAEQACAHgDAGIgBABQgDAFgGAEQgEACgFABIgDgBgAgfhrQgRAWgJAVQgKAYACAaQADAYAOARIACACIAUAQIAKAIIAKAHQAGAGAHAKQAGAGAFAIIAFAJIACADIABgGIAEgXIACgKQAEgVAGgRIAIgQIAFgJIAFgHIAAgHIgBgEIAAgEIACgXQABgIgBgRQgCgagcgdQgMgJgVgEQgTATgKAMg");
	this.shape_43.setTransform(-49.9988,489.9969);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#00FF00").s().p("AAVB7IgFgKIgKgQQgHgMgGgGIgKgJIgKgIIgTgSIgCgBQgOgSgCgZQgBgaAKgZQAJgVASgWQALgNARgSQAXAFAMALQAbAeADAbQAAAQgBAJIgFAaIAAAEIAAAFIAAAHIgFAHIgFAKIgIAQQgHARgEAVIgCALQgDAMgBALIgBAGIgCgDg");
	this.shape_44.setTransform(-25.9481,495.025);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#009900").s().p("AAYCrIABgHIgBgLIAAgDIgBgCIgFgFIgHgIQgDgDgGgMIgCgHQgSgggdgaIgIgIIgNgKIgFgGQgHgJgDgJIgBgCQgBgIACgLIACgUIgBgSQgBgKACgGQABgNAKgQIAEgHIAQgYIALgPIAPgRIAEgEQAMgLAIgBQAHgCAIADIAKAEIAJAGQAJAGAJAJQAMAOAIASIAEAJQAHASACASIAAAOIgBALIAAACIgBAGIgBAKIgBAMIAEASQABAFgBAEQgBAFgDACIgHgBIgCgBIgBAFIgIAOIgCAFIgEAJIgBAIIgEAUQgDARgIAIQAFAEAAAHQAAAHgFAJIADAFIACADIABAFQACAHgDAFIgBACQgDAFgGAEQgEADgFAAIgDgBgAgchxQgSAWgJAVQgLAZABAaQACAZAOASIACABIAUASIAKAIIAJAJQAHAGAGAMIAKAQIAGAKIACADIAAgGQABgLADgMIACgLQAEgVAHgRIAIgQIAGgKIAFgGIAAgHIgBgFIABgFIAEgaQACgJgBgQQgCgbgcgeQgMgLgWgFQgSASgKANg");
	this.shape_45.setTransform(-25.8833,496.925);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#00FF00").s().p("AALB5QgMgbgKgLQgFgHgOgMIgTgTQgQgTAAgcQgBgaALgZQAJgVATgXQAMgOAXgYQA9AzgDAuQgBAIgEARQgFAPgBAIQAAAGABAHIgFAHQgJAOgFANQgJAUgFAdQgEAQgBANIgHgOg");
	this.shape_46.setTransform(-1.6447,501.55);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#009900").s().p("AAVCxQACgKgBgOIAAgCQgHgFgFgJQgDgEgIgTQgTgngjgfIgSgQQgIgKgDgKQgBgIACgMQADgQAAgEIgCgSQgBgKABgHQABgNAKgQQAUgjAcgdQAPgPAJgBQAMgBAOAJQAgAUAPAkQARAkgIAkQgFAYABAIIAFASQACAMgGAFQgFgBgFgDIgBAGIgIAOQgFAJgCAFIgFAdQgDAQgIAJQAKAHgLAUIAEAFQACADABAFQACAHgDAGQgDAGgHAEQgEADgFAAIgDAAgAgah3QgTAWgJAWQgLAZABAaQAAAbAQAUIATATQAOAMAFAGQAKALAMAbIAHAPQABgOAEgQQAFgdAJgUQAFgNAJgOIAFgHQgBgFAAgHQABgIAFgQQAEgRABgIQADgug9gyQgXAYgMAOg");
	this.shape_47.setTransform(-1.7019,503.8347);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#00FF00").s().p("AAJB1IgCgEQgHgRgHgJQgCgFgDgDIgNgNIgGgGIgSgTIgEgFQgLgRgBgWIAAgCQgBgPAEgOQANgdAGgJQAHgMALgMIAjgiQAQANALAOQAQAQAHASQAIARgCASIgBAJIgDAPIgFAXIAAABIAAALQgDADgCAEIgGAMIgIAOQgKATgGAaIgDAMIgDAQIgHgOg");
	this.shape_48.setTransform(21.9841,493.2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#009900").s().p("AATCrIgBAAIAAgDQABgEAAgGIgBgKIAAgDIgHgHIgEgHIgGgJIgFgOIgGgLQgJgPgKgOQgMgPgPgNIgIgHIgKgJIgCgCQgHgJgCgJQgBgHACgLIAAgCIADgPIAAgFIAAgDIgBgHIAAgHQAAgGABgGIAAgEQACgNAKgPIAHgKQASgbAYgVIACgCQANgLAIgCIABAAQAMgBANAJQANAIAJAKQAPAQAJAWIACAGQAGARACAPQABAKAAALIgCANIgCAIIgCASIAAAFQABAFAEANQABALgFAFQgFAAgEgCIgBADIgBACIgIAOIgFAKIgBAEIgFATIgCAIQgDAPgJAIQAFAEgBAIQgBAFgFAIIADAEQACADABAEQABAGgDAFIgBACQgDAFgFADIgEACIgDAAIgEAAgAgYh0QgLAMgHAMQgGAJgNAcQgEAPABAOIAAADQABAXALAQIAEAFIASATIAGAGIANANQADADACAFQAGAJAIAQIACAFIAHAOIADgQIADgMQAGgaAKgTIAIgOIAGgMQACgEADgDIAAgKIAAgBIAFgYIADgQIABgJQACgRgIgSQgHgRgQgRQgLgNgQgNIgjAig");
	this.shape_49.setTransform(21.8646,495.245);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#00FF00").s().p("AAHBxIgCgEQgHgQgGgKIgGgIIgMgNIgGgGIgSgTIgDgGQgLgQgCgWIAAgCQABgPAEgOQANgaAGgIQAIgMALgMIAjgdQAQANAKANQAPARAIARQAHARgBARIgBAJIgDAQQgEAOgBAJIAAABIAAALIgFAHIgGAMIgIAMQgMASgGAXIgDAKIgDAQIgIgOg");
	this.shape_50.setTransform(45.5833,484.85);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#009900").s().p("AAQClIgBAAIABgDIgBgKIAAgKIAAgDIgHgHIgEgGIgEgKIgGgNIgGgMIgSgbQgMgQgPgNIgIgHIgKgJIgCgCQgGgJgDgIQgBgHACgLIAAgCIAEgPIAAgFIAAgCIAAgIIAAgGQAAgGABgFIABgEQACgNALgOIAGgKQATgYAZgTIABgBQAOgLAIgBIABAAQAMAAANAIQALAJAKAJQAOARAIAWIACAFQAGARABAPIACAUIgBAMIgCAJIgCARIAAAFIAEATQABAKgFAGIgIgCIgBADIgBACIgHAOIgFAKIgCADIgGATIgCAHQgEANgIAIQAEADgCAIQgCAEgFAIIADADQACADAAADQABAGgEAEIAAABQgDAEgFADIgEACIgEAAIgDAAgAgVhyQgLAMgIAMQgGAIgOAaQgEAOAAAPIAAACQACAXALAPIADAGIASATIAFAGIANANIAFAIQAGAKAHAQIADAEIAHAOIADgQIAEgKQAGgXALgSIAJgMIAGgMIAEgHIAAgLIAAAAQABgJAEgPIAEgQIAAgJQABgRgHgRQgHgRgQgRQgKgNgPgNIgjAdg");
	this.shape_51.setTransform(45.4333,486.65);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#00FF00").s().p("AAFBtIgDgEQgHgRgGgIIgFgJIgMgOIgFgFIgRgUIgDgFQgLgSgCgUIAAgDQAAgNAFgOIAVggQAIgLALgMIAjgZQAPANAJANQAQARAHARQAHASgBARIgBAIIgDAPIgEAWIAAABIAAAMQgDACgCAFIgGAMIgJAMQgMAPgHAUIgEAJIgEAOIgHgMg");
	this.shape_52.setTransform(69.2267,476.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#009900").s().p("AANCeIgBAAIAAgCIAAgKIgBgKIAAgCIgGgIIgEgGIgEgKIgGgNIgGgLIgRgcQgMgPgOgNIgIgHIgKgJIgCgCQgHgJgCgHQgBgIACgLIAAgCIAEgPIABgDIAAgCIgBgIIABgGQAAgGACgFIABgEQADgMALgOIAHgJQATgVAZgRIABgBQANgKAJAAIABAAQAMAAAMAJQAMAIAJAKQAOAQAHAWIACAGQAFARACANIACAVIgBAMIgCAIIgCAQIAAAFIAEATQABALgFAFQgEAAgEgBIgBADIAAACQgBADgHALIgFAJIgBAEQgCACgFAPIgCAGQgFANgJAHQADADgCAHIgHAKIACADQACACAAADQAAAFgDADIgBABQgCADgFADIgEACIgCAAIgFgBgAgThvQgLALgIALIgVAgQgFAOAAANIAAADQACAWALAQIADAFIARAUIAFAGIAMANIAFAJQAGAJAHAQIADAEIAHANIAEgPIAEgJQAHgUAMgPIAJgMIAGgMQACgEADgDIAAgLIAAgBIAEgXIADgPIABgIQABgRgHgSQgHgRgQgQQgJgNgPgNIgjAZg");
	this.shape_53.setTransform(69.0083,478.0583);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#00FF00").s().p("AACBpIgCgFQgHgPgGgJIgFgIQgDgHgIgIIgFgFQgLgLgGgKIgDgFQgLgRgCgVIAAgCQABgNAFgNIAWgeQAIgLAMgLIAigUQAPAOAJAMQAPAPAHATQAHARgBAQIAAAJIgDAOIgEAXIAAABIgBALIgEAIIgFALIgKAKQgOAOgIASIgEAHIgEAOIgIgMg");
	this.shape_54.setTransform(92.8517,468.15);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#009900").s().p("AAKCYIAAAAIgBgCIgBgJIAAgKIAAgCIgGgJIgDgGIgEgJIgGgNIgFgMQgJgLgIgQQgMgPgOgNIgIgHIgKgIIgCgCQgGgIgDgJQgBgHADgLIAAgCIAEgPIAAgCIABgDIAAgHIABgFQAAgGACgFIACgEQADgMALgNIAHgIQAUgTAagPIABgBQAMgIAKAAIABAAQALABANAJQAKAIAJAKQANAQAHAVIACAGQAFARABANIADAUIAAAMIgCAIIgCAQIAAAFIADATQABAKgFAFQgDABgEAAIgBACIAAACIgHAOIgFAJIgCAEQgCACgFAOIgDAGQgFALgKAGQADADgDAGIgHAJIABACQAAAAABABQAAAAAAABQAAAAAAABQAAAAAAABQAAAEgEACIAAACQgCACgFACIgEACIgCAAIgFgBgAgQhtQgMALgIAKIgWAfQgFAMgBAOIAAACQACAWALAQIADAFQAGAJALAMIAFAFQAIAIADAGIAFAJQAGAIAHAQIACAFIAIAMIAEgPIAEgHQAIgRAOgOIAKgKIAFgMIAEgHIABgMIAAAAIAEgXIADgOIAAgJQABgQgHgSQgHgSgPgPQgJgNgPgNIgiAUg");
	this.shape_55.setTransform(92.5857,469.4903);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#00FF00").s().p("AAABlIgCgFQgHgPgGgJIgEgJQgEgGgHgHIgFgHIgQgUIgDgGQgLgRgCgUIAAgCQABgNAGgNIAXgbQAIgJAMgLIAjgQQAOANAIANQAPAOAHASQAGASAAAQIgBAIIgCAOIgEAXIAAABIgBAMIgEAGIgFAMIgKAKQgQAMgIAOIgEAFIgFAPIgIgMg");
	this.shape_56.setTransform(116.4833,459.8);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#009900").s().p("AAHCSIAAAAIgBgCIgCgJIAAgKIAAgCIgEgIIgEgHIgEgJIgGgMIgFgMQgIgKgIgQQgLgQgPgNIgHgGIgKgJIgCgCQgHgHgCgJQgBgHADgLIAAgCIAEgPIABgCIABgCIgBgHIACgFQABgGACgEIACgEQAEgMALgMIAHgIQAVgPAagNIABgBQANgIAJABIABABQAMABALAIQALAIAIAKQANARAGAVIABAGQAFARABAMIAEAUIAAALIgCAIIgCAQIAAAFIADATQAAAJgEAGIgGABIgBACIgBACIgHAOIgFAJIgCADQgCADgGANIgDAFQgGAKgJAFQABADgDAFIgIAHIABACQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBACgEACIAAABIgHADIgEACIgBAAIgFgBgAgOhqQgMALgIAJIgXAcQgGAMgBANIAAACQACAWALAQIADAFIAQAVIAFAGQAHAIAEAGIAEAIQAGAJAGAQIADAEIAIAMIAFgOIAEgGQAIgOAQgMIAKgKIAFgLIAEgHIABgMIAAgBIAEgWIACgOIABgJQAAgQgGgRQgHgTgPgOQgIgNgOgNIgjAQg");
	this.shape_57.setTransform(116.1732,460.8991);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#00FF00").s().p("AgBBhIgDgEQgHgRgGgIIgEgJQgEgGgHgHIgFgHIgPgUIgDgGQgKgQgCgVIAAgCQABgMAGgMIAZgaQAHgJANgKIAigMQAPAOAHANQAOANAHATQAGARAAAQIAAAJIgCAMIgEAYIAAAAIgBALIgEAIIgFALIgLAIQgRAKgIAMIgEAEIgGAOIgHgLg");
	this.shape_58.setTransform(140.1125,451.45);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#009900").s().p("AAECLIAAAAIgBgBIgDgJIAAgKIAAgCIgDgIIgEgHIgEgJIgGgMIgEgMQgJgJgHgRQgLgPgOgNIgHgGIgKgJIgCgBQgHgIgCgJQgBgHADgLIAAgBIAEgPIABgCIABgBIAAgHIACgFQABgGADgEIACgEQAEgMAMgLIAHgHQAWgNAagKIABgBQANgHAKACIABAAQALACALAIQAKAIAIAKQAMARAFAVIACAGIAFAdIAEATIABALIgCAIIgCAPIAAAGIADASQAAAJgEAGIgGACIgBACIAAACIgHAOIgFAIIgCADQgDAEgGALIgDAEQgHAJgJAFQAAACgDAFIgJAFIABACIgBADQgBABgEABIAAABIgGACIgEACIgGgCgAgLhoQgNALgIAIIgZAaQgGAMgBAMIAAACQACAVALAQIADAGIAPAVIAFAGQAHAIADAGIAEAIQAGAJAHAQIACAEIAIALIAGgNIAEgFQAJgLARgKIALgIIAFgMIADgHIACgMIAAAAIADgWIACgOIAAgJQABgQgHgRQgHgTgOgNQgHgNgOgOIgiAMg");
	this.shape_59.setTransform(139.769,452.3109);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#00FF00").s().p("AgDBcIgDgEQgHgPgGgJIgEgJQgDgGgHgIIgEgFIgPgWIgDgFQgKgRgDgVIAAgCQACgMAGgLIAagXQAIgIANgKIAigHQAOANAHANQAOANAGATQAGARABAQIgBAIIgBANIgEAWIAAABIgBAMIgEAHIgEAMIgLAHQgTAIgJAJIgFADIgGAMQgEgFgDgGg");
	this.shape_60.setTransform(163.725,443.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#009900").s().p("AABCFIAAAAIgBgBIgCgJIAAgJIAAgCIgEgJIgDgGIgEgKIgGgLIgEgMQgJgIgHgSQgKgPgOgNIgHgGIgKgIIgCgCQgHgIgCgIQgBgIADgKIAAgCQACgKADgEIABgBIABgBIAAgHIADgFQABgFAEgEIABgEQAGgLAMgLIAHgHQAWgKAagIIABgBQANgFAKACIABAAQALADALAIQAKAIAHAKQAMARAFAUIABAGIAFAcIAFAUIAAAKIgBAHIgCAQIAAAFIACATQAAAJgEAGIgFADIAAABIgBACQgCAFgFAJIgFAIIgCADIgJAOIgEADQgHAIgKAEIgEAGIgJAEIAAABIgBACQgCABgEgBIAAABQgCgBgEACIgEACIgGgCgAgJhlQgNAKgIAIIgaAXQgGALgCAMIAAACQADAVAKAQIADAGIAPAVIAEAGQAHAIADAGIAEAJQAGAJAHAPIACAEQADAGAFAFIAGgNIAFgDQAJgIATgJIALgHIAEgLIAEgIIABgLIAAgBIAEgWIABgNIABgIQgBgQgGgRQgGgTgOgNQgHgNgOgNIgiAHg");
	this.shape_61.setTransform(163.3357,443.7077);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#00FF00").s().p("AgGBZIgDgFQgGgPgGgIIgEgJQgDgHgHgIIgDgFQgJgMgFgLIgDgFQgKgQgDgWIAAgBQACgLAGgLIAcgVIAWgRIAhgDQAOANAGANQANANAGAUQAHAQAAAQIAAAHIgBAOIgEAWIgBALIgDAIIgFAMIgMAFQgTAHgKAGIgFACIgIAMIgHgKg");
	this.shape_62.setTransform(187.35,434.75);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#009900").s().p("AgBB/IAAAAIgCgBIgDgIIAAgJIAAgDIgDgIIgDgHIgEgJIgGgLIgEgMQgIgHgHgTQgKgOgNgNIgHgGIgKgIIgCgCQgHgIgCgJQgBgHADgKIAAgCQACgKADgEIACAAIABgBQgBgEABgDIADgFQACgEAEgEIABgEQAGgLANgKIAHgGQAXgIAagGIABAAQANgEALACIABAAQAKADALAJQAJAHAHAKQAMARADAVIACAGIAEAbIAFATIABAKIgBAHIgCAQIAAAFIACASQAAAJgEAGIgFAEIAAABIgBADQgBAFgFAIIgFAIIgCADIgKAMIgFADQgHAHgLADIgFAFIgJADIgBAAIgCABIgGgBIAAABQgBgCgEABIgEADIgFgDgAgGhiIgWAQIgbAVQgHALgCAMIAAABQADAVAKAQIADAGQAGAKAIAMIAEAFQAGAIADAHIAEAJQAGAIAHAPIADAFIAHAKIAHgMIAFgCQAKgGAUgGIALgGIAFgLIADgIIACgMIADgWIABgNIAAgIQAAgQgGgQQgHgUgNgMQgGgNgOgNIghADg");
	this.shape_63.setTransform(186.9357,435.1167);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#00FF00").s().p("AgIBVIgDgEQgHgPgFgJIgEgJQgDgGgGgIIgEgGIgNgWIgCgGQgKgQgDgVIAAgBQACgLAHgLIAdgSIAWgPQAVgBAMACQAOANAEANQAOAMAGATQAGARAAAQIAAAGIgBAOIgCAWIAAAAIgCAMIgDAHIgFAMIgMAEIgfAIIgFAAIgIAMIgIgKg");
	this.shape_64.setTransform(210.9875,426.3438);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#009900").s().p("AAJB6IAAAAQAAgBgBAAQAAAAgBAAQAAgBgBABQgBAAgBAAIgEADIgEgDIAAAAIgCgBQgCgBgCgIIAAgIIAAgDIgCgIIgDgHIgEgJIgFgLIgEgMQgJgGgGgTQgJgPgOgMIgHgGIgJgIIgDgCQgGgIgCgIQgBgIADgKIAAgBQACgKADgEIACAAIABgBQAAgEABgCIADgFQACgEAFgEIABgEQAHgLANgJIAHgFIAygJIABAAQAOgDAKACIABABQALADAJAJQAKAHAGAKQALARADAVIABAGIAEAbIAGASIABAKIgBAHIgBAPIAAAGIAAASQAAAIgDAGIgEAFIAAABIgBACQgCAGgFAIIgEAHIgDADIgLALIgEADQgJAFgKADIgHAEIgKABIgBAAIgCAAIgHgDgAgEhgIgWAQIgdASQgHALgCALIAAABQADAUAKASIADAEIANAWIAEAGQAGAIADAHIADAJQAGAIAGAPIAEAFIAHAJIAIgLIAFgBIAggHIAMgFIAEgLIADgIIACgLIAAgBIADgVIABgOIAAgHQgBgQgFgQQgHgUgNgMQgFgNgNgNIgYgBIgKAAg");
	this.shape_65.setTransform(210.5357,426.5932);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#00FF00").s().p("AgKBTIgEgEQgGgPgFgIIgEgJQgCgHgGgIIgEgGIgMgXIgDgFQgKgRgDgUIAAgBQACgLAIgKQAXgLAHgFQAIgGAOgIQAWACAMADQANAOAEANQANAKAGAVQAGAQAAAOIABAIIgBAOIgCAVIgDAMIgDAIIgDALIgNADQgXADgLAAIgFgBIgIALIgIgJg");
	this.shape_66.setTransform(234.625,417.775);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#009900").s().p("AARB5IgBAAIgDgBIgIgFIAAAAQAAgDgEABIgDACIgFgDIAAAAIgCgBQgCAAgDgIIABgIIAAgCIgDgKIgDgGIgDgJIgFgLIgDgMQgJgFgFgTQgKgPgNgMIgHgGIgKgIIgCgCQgGgIgCgIQgBgIADgKIAAgBQACgKADgEIACABIACgBQAAgDABgDIADgEIAHgIIADgDQAHgLANgJIAHgEIAzgEIABAAQAOgCAKADIABABQALAEAJAIQAJAIAGAKQAKARADAUIABAGIADAaQACAHAFALIACAJIgBAHQAAAHgCAJIAAAFIAAASQAAAIgDAGIgEAGIAAABIgBACIgGANIgEAHIgDADIgMALIgFACQgJADgKACIgIADIgGABIgFgBgAgYhRQgHAFgXALQgIAKgCALIAAAAQADAVAKARIADAGIAMAVIAEAGQAGAIACAHIAEAJQAFAIAGAPIAEAFIAHAJIAJgMIAFACQALAAAXgDIANgDIADgMIADgIIADgLIACgWIABgNIgBgHQAAgPgGgRQgGgUgNgLQgEgNgNgNQgMgEgWgCQgOAJgIAGg");
	this.shape_67.setTransform(234.1375,418.2011);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#00FF00").s().p("AgNBRIgDgEQgGgPgGgIIgDgJQgCgIgGgIIgDgFIgMgXIgDgFQgJgRgDgVIAAAAQACgKAIgKQAYgJAIgEIAWgOQAWAFALAFQANANAEANQAMALAGAUQAGAQABAOIAAAIIAAANIgCAWIgDALIgDAIIgDALIgOACQgYACgLgDIgGgDIgIAKQgFgDgEgFg");
	this.shape_68.setTransform(258.2625,409.2);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#009900").s().p("AAPB2IgCgBIgDgBIgIgHIgBAAQAAgEgCABIgEACIgFgEIAAAAIgDgBQgCABgCgIIAAgIIAAgDIgCgJIgDgGIgDgJIgFgLIgDgMQgIgEgFgUQgJgOgNgMIgHgGIgKgIIgCgCQgHgIgBgIQgBgIADgJIAAgCQACgKADgEIADACIACgBQgBgDABgCIAEgFIAIgHIADgDQAHgLAOgIIAIgDIAzABIABAAQAOgBAKADIABABQALAEAJAJQAIAIAGAJQAKASACAUIAAAFIAEAaIAGARIADAKIgBAHQAAAGgCAJIAAAFIAAASQgBAHgCAHIgDAHIAAABIgBACQgCAGgEAGIgFAIIgCACQgGAFgHAEIgFACQgKACgLACIgJABQgGABgFgCgAgWhRQgHAEgYAJQgJAKgCAKIAAAAQADAVAKARIADAGIALAWIAEAFQAFAIADAIIADAJQAFAIAGAPIAEAEQADAFAEADIAKgKIAFADQAMADAYgCIANgCIAEgLIADgIIACgLIACgWIAAgNIAAgIQgBgOgFgQQgGgUgNgLQgDgNgNgNQgLgFgXgFIgWAOg");
	this.shape_69.setTransform(257.7375,409.8);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#00FF00").s().p("AAJBRIgGgEIgJAKQgFgEgEgDIgEgFQgFgPgFgIIgDgJQgDgHgFgJIgDgFIgLgWIgDgHQgJgRgEgUIAAAAQADgKAJgJQAZgHAHgEIAXgNQAXAHALAIQAMANADANQAMAKAGAUQAFAQABAPIABAHIAAANIgCAVIgDAMIgDAIIgDALIgOABQgZgBgMgGg");
	this.shape_70.setTransform(281.875,400.65);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#009900").s().p("AANB1IgDgCIgEgCIgHgJQAAgFgEAAIgEADIgEgEIgDAAQgDAAgCgIIAAgIIAAgCIgBgKIgDgGIgDgJIgFgKIgCgMQgJgDgEgVQgJgNgNgNIgGgGIgKgIIgCgCQgHgIgCgHQgBgIADgKIAAgBQADgKAEgEQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAAAIACAAQAAgEABgBIAEgFQAEgDAFgDIADgEQAIgKAOgHIAIgDIA0AGIABAAQAOAAALAEIABABQAKAGAJAIQAHAHAGAKQAJARABAUIABAGIADAZQABAGAGAKIADAKQAAAEgBADQAAAGgCAJIAAAFIAAARIgDAPIgDAIIgBACIgFANIgFAGIgDADQgFAFgIADIgGABIgVACIgLABIgLgDgAAOBMQAMAFAaABIAOgBIADgLIADgIIACgLIACgVIAAgOIAAgHQgCgOgEgQQgHgVgMgKQgDgNgMgMQgLgJgXgGIgWAMQgIAFgZAHQgIAIgDALIAAAAQADAUAKARIACAGIAMAWIACAGQAGAIACAHIADAKQAFAIAGAOIAEAFQADAEAGADIAIgKIAGAFg");
	this.shape_71.setTransform(281.3208,401.2);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#00FF00").s().p("AABBJIgJAKQgKgGgDgGQgGgPgFgHQgCgMgIgOIgPgiQgKgSgDgTQADgJAJgJQASgBAQgIIAegOQAlAZADAXQAMAIAGAVQAGATABASQABAQgCASIgJAfQgugBgOgQg");
	this.shape_72.setTransform(305.5167,392.3);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#009900").s().p("AAXB4QgTgFgJgPQABgJgIAGIgEgFIgDAAQgDABgDgIQABgKgBgKIgGgPQgGgLgBgLQgIgCgEgVQgLgRgRgPIgMgKQgGgIgCgIQgBgHADgKQADgLAEgDQABADAEAAQgBgEACgCQAFgGAJgEQALgQAXgGIA2ALQAOABALAFQAVALALAVQAKAUgBAXQABATACAGQABAEAHALQAEALgCAFQABAGgCAJQgBAXgFAWQgEANgHAIQgIAIgJACIgoAAgABDBXIAJgfQACgSgBgPQgBgTgGgSQgGgVgMgJQgDgXglgZIgeAOQgQAIgSABQgJAJgDAJQADAUAKARIAPAjQAIANACAMQAFAHAGAPQADAGAKAGIAJgKQAOARAuAAg");
	this.shape_73.setTransform(304.908,392.575);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#00FF00").s().p("AgBBGIgKAHIgFgDQgFgFgCgEIgEgKIgGgLIgBgCIAAgDQgCgLgHgLIgBgDIgOggIgFgMIgIgaIAGgIIAggKIAUgHIAVgIQAWAPALAPQAGAJACAKQAHAGAFAKQADAHACAIQAEANABANIAAAMQABAOgCARIgBACIgKAcQgvgCgNgSg");
	this.shape_74.setTransform(320.255,377.475);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#009900").s().p("AAqB3IgXgCQgSgGgKgQIAAgCQABgHgHAFIgEgEIgDgBQgCAAgCgEIgCgDIgBgPIgBgFIgEgMIAAgDIgCgEIgCgEQgCgHAAgGIgBAAQgFgEgDgJIgDgLIgEgHQgHgLgIgJIgIgIIgIgHIgDgDIgBgBIgEgFQgDgEgBgFIAAgBQAAgFABgGIABgGIADgHIAEgFQACADADAAIABgDIABgBIAAgBQAEgEAIgDIADgBQAFgHAIgDQAJgGAMgCQAZAHAaAEIAEABQAJABAIACIAIADIALAHQAHAGAFAHQAFAHADAGIAGALIAEAOQACAJgBAKIAAAGIACATIAHARQAEAKgCAHIAAAKIgBAEQgBAMgCAKQgCALgEAKIAAABQgFALgIAHQgIAIgJABIgRgBgABBBZIALgcIAAgCQACgRAAgPIgBgLQgBgOgEgMQgBgJgDgGQgFgKgHgHQgCgJgHgKQgKgOgXgPIgUAIIgVAHIggAKIgFAIIAHAaIAGAMIAOAfIABAEQAGALADALIAAADIABACIAFAKIAEALQADAEAFAEIAFAEIAJgHQAOASAuACg");
	this.shape_75.setTransform(319.6163,377.6);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#00FF00").s().p("AgEBEIgJAFIgFgFIgHgIIgEgLIgGgKIAAgDIgBgDQgCgLgGgMIgBgDIgNggIgFgMQgFgNgDgNIAGgHIAhgGIAVgGIAUgHQAXAPALAQQAHAJACAKQAHAHAEALIAFAOQADAOABANIAAAMQAAAPgDARIAAACQgGAIgHAQQgvgDgNgTg");
	this.shape_76.setTransform(335.0036,362.625);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#009900").s().p("AAlB1IgWgDQgRgHgKgQIAAgCQAAgHgHAEIgDgFIgDgBQgCAAgCgEIgCgEIgCgNIgBgGIgEgMIAAgDIAAgDIgCgEQgCgHgBgHIgBgBQgEgDgCgJIgEgMIgEgGIgOgWQgEgCgEgFIgIgIIgDgDIgBgCIgEgEQgDgFgBgEIAAgBQgBgGACgHIABgEIAEgHIAEgFQABAEAEABIABgCIAAgCIAAgBQAGgDAIgCIACgBQAFgFAJgDQAJgEAMgCQAZAIAbAEIAEACIARADQAEABAEACIALAHQAGAFAGAJIAIANIAAAAIAGALIAFAOQABAJAAALIAAAGIACATQABAHAFALQADALgBAGIgBAKIgBAEQgBAMgDALQgDAKgFAJIgBAAQgFALgJAGQgIAGgKABIgRgDgAA/BaQAHgPAGgJIAAgCQADgRAAgPIAAgLQgBgOgDgNIgFgPQgEgLgHgHQgCgJgHgKQgLgQgXgPIgUAHIgVAGIghAHIgGAGQADANAFANIAFAMIANAgIABAEQAGALACALIABADIAAADIAGALIAEAKIAHAIIAFAFIAIgFQAOATAvADg");
	this.shape_77.setTransform(334.32,362.6);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#00FF00").s().p("AgGBBIgKACIgEgEIgHgJIgEgLIgFgLIgBgCIAAgEQgCgLgGgMIgBgDIgMghIgGgMIgIgaIAHgFQAXgBALgCIAVgFIAVgFQAXAOAMARQAGAKADAKQAGAHAFALIADAPQADAOAAAOIAAAMQAAAOgDASIgBACQgHAHgIAOQgugFgNgUg");
	this.shape_78.setTransform(349.7625,347.825);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#009900").s().p("AAhB0IgWgFQgRgIgJgRIgBgCQAAgGgGACIgDgFIgDgBQgCgBgCgEIgCgDIgDgOIgBgFIgEgMIAAgDIABgDIgCgEQgCgGAAgIIgBAAQgEgFgCgHIgFgOIgDgHIgNgWQgFgCgDgFQgFgFgCgEIgDgDIgCgBIgEgFQgDgEgBgFIAAgBQgBgGACgGIACgFIAEgHQAAgBABAAQAAgBAAAAQABAAAAgBQABAAAAAAQACAEADABIABgCIABAAIAAgBQAGgDAIgCIACAAQAFgFAKgBQAJgCAMgBQAZAIAbAFIAFABQAKABAHACIAIADIALAHQAGAGAFAIIAJAPIAGALIAFAOQACAJAAAMIAAAFIACAVQABAHAEALQACAKgBAHIgBALIgBAEQgCAMgDAKQgDAKgHAIIgBAAQgGAJgJAFQgJAFgKAAIgRgDgAA9BcQAIgOAHgHIABgCQADgSAAgOIAAgMQAAgOgDgOIgEgPQgEgLgHgHQgCgKgHgKQgLgRgXgOIgVAFIgWAFQgLACgWABIgHAFIAIAaIAFAMIANAhIABADQAFAMACALIAAAEIABACIAGALIAEALIAGAJIAFAEIAIgCQAOAUAvAFg");
	this.shape_79.setTransform(349.0231,347.625);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#00FF00").s().p("AgJA+IgJAAIgEgFIgGgIIgFgMIgFgLIgBgDIAAgDQgCgMgFgLIgBgDQgEgQgIgSIgFgMIgIgaIAHgEQAYABALgBIAWgDIAVgDQAXAMAMASQAHALACAKQAHAHAEAMIADAPQADAOgBAPIAAAMQgBAPgDASIgBACQgJAGgJAKQgugFgNgWg");
	this.shape_80.setTransform(364.5286,333);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#009900").s().p("AAuB3IgRgEIgWgHQgQgJgKgRIAAgCQAAgHgGACIgDgFIgDgCIgEgFIgCgEIgEgNIgBgFQgCgDgCgJIABgCIABgDIgCgFQgCgFAAgIIgBgBQgDgFgCgHIgFgOIgDgIIgMgWQgFgDgDgFQgFgFgCgFIgDgCIgBgBIgFgFQgDgFgBgFIAAgBQgBgGACgGIACgFIAEgHQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAQABAEAEABIABgBIABAAIAAAAQAGgDAIgBIADAAQAFgEAKABQAJgCAMAAQAZAJAcAFIAEABQALABAHACIAIAEQAGADAFAEQAGAGAFAJIAIAPIAHALIAGAPQACAJAAALIAAAGIABAVQABAIAEALQACAKgCAHIgBALIgBAEQgCANgEAJQgEAKgIAHIgBAAQgHAIgKAEQgIADgHAAIgEAAgAA6BdQAJgLAJgGIABgBQADgTABgOIAAgMQABgPgDgPIgDgOQgEgMgHgHQgCgLgHgKQgMgSgXgNIgVADIgWAEQgLABgYgBIgHADIAIAbIAFAMQAIASAEAQIABACQAFAMACAMIAAADIABADIAFALIAFALIAGAJIAEAFIAJAAQANAVAuAGg");
	this.shape_81.setTransform(363.7357,332.635);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#00FF00").s().p("AgNA8IgIgCIgEgGIgGgJQgCgHgCgFIgGgKIAAgEIAAgDQgCgMgEgLIgBgEQgEgPgIgTIgFgMIgIgbIAIgBQAYADALAAIAXgCIAWgCQAXAMAMATQAHALADAKQAGAIADAMIADAQQACAOAAAPIgBAMQgBAPgEATIgBABQgKAFgKAIQgugHgOgWg");
	this.shape_82.setTransform(379.305,318.15);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#009900").s().p("AAqB4IgRgFIgWgJQgQgKgJgSIgBgCQAAgGgFABIgDgGIgDgBIgEgGIgCgEIgFgNIgCgFQgCgDgBgJIABgCIACgCIgCgFQgBgFAAgJIgBgBIgFgMIgFgPIgDgIQgHgNgEgKQgFgCgEgGQgEgFgBgFIgDgDIgCgBIgFgFQgEgEgBgGIAAAAQAAgGACgHIACgEIAFgHIADAAQACAEADACIACgBIABABIAAgBQAGgCAIAAIADAAQAFgCAKABIAWABQAaAJAbAGIAFABQALABAHACIAIADIALAIQAGAGAFAJIAIAPIAAABIAHAMIAGAOQADAJAAAMIAAAGIABAWQABAIACALQACAKgCAIIgBAKIgBAFQgDANgEAJQgFAJgJAGIgBAAQgJAHgKACQgGACgHAAIgGAAgAhAhQIAIAbIAFAMQAIATAEAQIABADQAEALACAMIAAAEIAAADIAGAKQACAFACAHIAGAJIAEAGIAIACQAOAXAuAHQAKgJAKgFIABgBQAEgTABgOIABgNQAAgPgCgPIgDgPQgDgLgGgIQgDgLgHgLQgMgSgXgNIgXACIgWACQgLABgYgEIgIABg");
	this.shape_83.setTransform(378.4333,317.5167);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#00FF00").s().p("AgQA8QgEgBgDgEIgEgGIgFgJIgFgMIgGgLIAAgEIAAgDQgBgLgEgNIgBgDIgLgiIgFgNIgJgbIAJAAQAZAGALABIAYgBIAVgBQAYAMAMAUQAHAKADAMQAGAJADAMIADAOQACAQgBAPIgBANQgCAPgEATIgBABQgMADgLAHQgtgJgPgXg");
	this.shape_84.setTransform(394.0667,303.075);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#009900").s().p("AAlB7IgRgGQgMgEgJgGQgQgLgJgSIAAgDQgBgGgFAAIgDgGIgCgCIgEgGIgDgEIgGgMIgBgFQgDgEgBgIIACgCIADgCIgCgFQgBgFgBgIIAAgBIgEgOIgFgPIgEgIQgHgNgCgLQgGgCgDgGQgEgFgCgHIgDgBIgBgCIgFgFQgEgEgBgGIAAAAQgBgHADgGIABgEQADgFADgCIADACQACAEADACIACAAIABABIAAgBQAHgBAIAAIADABQAFgCALADIAWADQAZAKAdAGIAEABIASADQAEABAEADQAHADAEAEQAGAGAFAKIAIAQIAAAAIAIAMQAFAIACAHQACAJABAMIAAAFIAAAYQAAAIADALQABALgCAIIgCAKIgBAEQgDAPgEAHQgGAKgLAEIgBAAQgJAGgLACIgHABQgGAAgHgCgAg4g3IAFANIALAiIABADQAEAMABAMIAAADIAAAEIAGALIAFAMIAFAJIAEAGQADAEAEABQAOAXAuAJQALgHAMgDIABgBQAEgTACgPIABgNQABgPgCgQIgDgOQgDgMgGgJQgDgMgHgKQgMgUgYgMIgWABIgXABQgLgBgZgGIgJAAIAJAbg");
	this.shape_85.setTransform(393.1542,302.1531);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#00FF00").s().p("AgTA9QgEgCgDgFIgEgHIgFgJQgBgIgDgEIgGgLIAAgEIAAgDQgBgMgDgMIgBgEQgEgQgHgSIgEgOIgKgbIAKACQAaAJAKABIAZABIAWAAQAYAMAMAUQAIALADAMQAFAJADAMIADAQQABAPgBAQIgCANQgCAPgEAUIgCAAQgNACgLAEQgugJgPgZg");
	this.shape_86.setTransform(408.85,287.85);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#009900").s().p("AAhB/IgRgHQgMgFgJgHQgQgMgIgTIgBgCQgBgHgEAAQgBgEgCgDIgCgBIgEgHIgDgEIgHgMIgCgFQgCgEgBgIIADgCIADgBIgCgGIgBgNIAAgBIgEgOIgFgPIgEgJQgHgOgBgLQgGgBgEgHQgDgFgBgHIgDgCIgCgBIgFgFQgFgFgBgGQAAgGADgHIABgEQADgEADgCIAEADIAFAHIACAAIABABIAAAAQAHgBAIABIADABQAGAAAKADIAXAGQAaAKAcAGIAFABIASAEQAEABAEACQAHAEAEAEQAGAGAFAKIAIAQIAAABIAIANQAFAIACAGQADAJABAMIAAAGIAAAZQAAAIABALQABALgCAIIgCAKIgBAFQgDAPgFAHQgHAJgMADIgBAAQgLAFgLAAIgCAAQgJAAgJgCgAg4g5IAFANQAHATAEAQIABADQADAMABAMIAAAEIAAAEIAGAKQACAFACAIIAFAJIAEAHQADAFAEACQAOAZAuAJQAMgEANgCIABgBQAFgTACgPIABgNQABgQgBgQIgCgQQgDgLgFgJQgEgMgHgLQgNgUgXgMIgXgBIgYAAQgKgBgagJIgKgCIAJAbg");
	this.shape_87.setTransform(407.8527,286.7786);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#00FF00").s().p("AgWA+IgHgJIgDgHIgEgKIgFgMIgGgLIAAgEIAAgEQAAgMgDgMIgBgEQgEgQgGgTIgFgNIgKgbIALAEQAbALAKABIAZACIAXACQAXALAOAWQAHALADAMQAFAKADAMIACAQQABAPgCARIgCANIgHAjIgCAAIgbADQgtgLgPgag");
	this.shape_88.setTransform(423.645,272.625);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#009900").s().p("AAxCGQgKAAgLgEQgIgDgIgFQgMgGgJgIQgPgNgJgTIAAgCQgCgHgDgBIgDgHIgCgCIgEgHIgDgEIgIgMIgCgEQgDgFAAgHIADgCQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAIgBgGIgCgNIAAgBIgDgPIgFgPIgEgJQgHgPAAgLQgGgBgEgIQgDgFgBgHIgDgCIgCgBQgDgCgCgDQgFgFgBgGQgBgHAEgGIABgEQADgEAEgCIADAEIAFAIIACABIABABIABAAQAIgBAIADIACABQAGAAALAFIAXAIQAaALAdAGIAFABIASAEQAEABAEACQAHAEAEAEQAGAGAFALIAIARIAAABIAIAMQAGAJACAGQADAIABANIAAAHIAAAZIAAAUQAAAKgCAJIgCAKIgBAFQgEAPgFAHQgIAIgNACIgBABQgKACgKAAIgEAAgAg3g7IAEANQAHATADAQIABAEQADALAAANIABAEIgBAEIAGALIAFAMIAEAKIAEAHIAGAJQAOAaAvALIAbgDIACAAIAHgjIACgNQABgRgBgPIgCgRQgCgLgFgKQgEgMgHgLQgNgWgYgLIgXgCIgYgCQgLgBgagLIgLgEIAKAbg");
	this.shape_89.setTransform(422.5889,271.4286);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#00FF00").s().p("ABABoIgdgBQgtgNgPgbIgHgLIgDgIIgEgJQgCgKgDgEIgFgLIAAgEIAAgEQAAgMgDgNIgBgDQgDgQgGgUIgFgMQgEgPgGgNIAMAFQAcAOAKACIAZADIAXAEQAYAKAOAXQAHALAEANQAEAKADAMIABAQQABAQgDARIgCAOIgHAkIgDAAg");
	this.shape_90.setTransform(438.4393,257.45);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#009900").s().p("AAtCLQgLgCgLgEQgIgEgIgFQgLgHgKgIQgPgPgIgTIgBgDQgBgGgDgDIgDgGIgCgDIgEgHIgDgEIgJgMIgCgEQgEgGABgGIADgBIAFgCIgBgFQgBgEAAgJIAAgCIgDgPIgGgQIgDgJQgHgPABgLQgHgCgDgIQgDgFAAgIIgDgBIgCgBIgGgFQgFgFgBgGIAAgBQgBgGAEgHIACgEQADgEAEgCIADAGIAFAIIACACIABACIABAAQAIgBAIAEIADABQAFABAMAHIAXAJQAaAMAdAHIAGABQAMABAGACIAIAEQAHADAEAFQAGAGAEALIAIASIAAAAIAJANQAGAJACAGQAEAJABANIAAAHIgBAZIAAAVQgBAKgCAJIgCALIgBAEQgEAQgGAGQgIAIgPABIgBABIgNABIgMgBgAg4g9IAEANQAHATADAQIABAEQACALAAAOIAAADIAAAFIAGAKQACAFADAJIAEAJIADAIIAGAMQAPAbAuAMIAdABIACAAIAIgkIACgNQACgSgBgPIgBgRQgCgNgFgJQgEgNgHgLQgOgWgXgLIgYgEIgZgDQgKgCgcgNIgLgGQAFANAFAPg");
	this.shape_91.setTransform(437.3639,256.1125);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#00FF00").s().p("AA/BsIgggEQgtgOgPgcIgGgNIgDgJIgDgJQgDgKgCgEIgGgLIABgEIgBgEQAAgNgBgNIgCgDQgCgRgGgTIgFgOIgKgbIAMAHQAdAQAKADIAaAFIAXAEQAYAKAOAZQAHALAFANQAEAKACAMIABARQAAAQgDASIgCANIgIAlIgDgBg");
	this.shape_92.setTransform(453.25,242.45);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#009900").s().p("AAoCPQgLgCgLgGQgIgEgIgFQgLgIgJgJQgPgQgIgTIgBgDIgEgKIgDgHIgBgCQgCgGgDgCIgCgEIgKgMIgDgEQgEgGACgGIADgBQADgBADAAIgBgGQgBgDAAgKIAAgCIgCgPIgGgRIgEgJQgGgQACgLQgHgBgEgIQgCgGAAgIIgDgBIgDgCQgDgBgDgEQgFgFgBgGQgBgHAEgHIACgDQADgEAFgCIADAHIAFAJIACACIABACIABAAQAJABAIAEIACABIASAKQALAHAMAFQAbAMAeAHIAFABIASAEIAJAEQAGADAFAFQAFAFAFAMQAFAPADADIAAABIAJAOQAGAIADAFQADAKABAOIAAAGIAAAbIgCAVIgDAUIgCAKIgBAFQgFAQgHAGQgJAHgPAAIgCAAIgHAAQgKAAgKgCgAg4hAIAEANQAGATADARIABAEQACALgBAOIABAEIgBAFIAGAKQADAFACAJIADAJIADAJIAGAOQAPAcAuAOIAfAEIADAAIAIgkIADgOQACgRAAgQIgBgRQgCgNgEgLQgEgMgHgLQgPgYgYgKIgYgFIgZgFQgKgDgcgQIgNgHIALAcg");
	this.shape_93.setTransform(452.14,240.8375);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#00FF00").s().p("AghA9QgDgIgFgQQgEgRgEgHIgGgLQABgDAAgFQAAgQgCgOQgDgWgKgcQgEgPgGgNIANAJQAZARAOAFQAIADATADQAPADAJAEQAXAJAPAZQAOAWADAaQACAXgEAdIgMAzQhOgNgUgpg");
	this.shape_94.setTransform(468.0558,227.425);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#009900").s().p("ABCCXQglgBgfgXQgggXgMgkQgIgXgFgGQgDgFgKgKQgIgIADgIQAFgCAFABIgBgGIgBgPQAAgKgBgGIgKgbQgGgQADgMQgNgBAAgXQgDAAgCgCQgEgCgDgDQgFgFgBgHQgBgHAEgGQAEgHAGgDQADAKAIALIABADQAJABAJAFQAEACARAMQAlAYArAKIAYAEQAMAFAIAHQAFAGAEAMIAIATIAKAPQAHAIACAGQAFALAAATQAAApgJAmQgGAVgIAGQgIAHgOAAIgEgBgAg5hEQAKAcACAWQADAOgBAPQABAFgBAEIAGALQADAHAFARQAEAQAEAIQAUApBNANIAMgzQAFgdgCgXQgEgbgNgVQgPgZgXgJQgJgEgRgDQgSgDgHgDQgOgFgagRIgNgJQAGANAFAPg");
	this.shape_95.setTransform(466.94,225.6063);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_10}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_17},{t:this.shape_16}]},1).to({state:[{t:this.shape_19},{t:this.shape_18}]},1).to({state:[{t:this.shape_21},{t:this.shape_20}]},1).to({state:[{t:this.shape_23},{t:this.shape_22}]},1).to({state:[{t:this.shape_25},{t:this.shape_24}]},1).to({state:[{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_29},{t:this.shape_28}]},1).to({state:[{t:this.shape_31},{t:this.shape_30}]},1).to({state:[{t:this.shape_33},{t:this.shape_32}]},1).to({state:[{t:this.shape_35},{t:this.shape_34}]},1).to({state:[{t:this.shape_37},{t:this.shape_36}]},1).to({state:[{t:this.shape_39},{t:this.shape_38}]},1).to({state:[{t:this.shape_41},{t:this.shape_40}]},1).to({state:[{t:this.shape_43},{t:this.shape_42}]},1).to({state:[{t:this.shape_45},{t:this.shape_44}]},1).to({state:[{t:this.shape_47},{t:this.shape_46}]},1).to({state:[{t:this.shape_49},{t:this.shape_48}]},1).to({state:[{t:this.shape_51},{t:this.shape_50}]},1).to({state:[{t:this.shape_53},{t:this.shape_52}]},1).to({state:[{t:this.shape_55},{t:this.shape_54}]},1).to({state:[{t:this.shape_57},{t:this.shape_56}]},1).to({state:[{t:this.shape_59},{t:this.shape_58}]},1).to({state:[{t:this.shape_61},{t:this.shape_60}]},1).to({state:[{t:this.shape_63},{t:this.shape_62}]},1).to({state:[{t:this.shape_65},{t:this.shape_64}]},1).to({state:[{t:this.shape_67},{t:this.shape_66}]},1).to({state:[{t:this.shape_69},{t:this.shape_68}]},1).to({state:[{t:this.shape_71},{t:this.shape_70}]},1).to({state:[{t:this.shape_73},{t:this.shape_72}]},1).to({state:[{t:this.shape_75},{t:this.shape_74}]},1).to({state:[{t:this.shape_77},{t:this.shape_76}]},1).to({state:[{t:this.shape_79},{t:this.shape_78}]},1).to({state:[{t:this.shape_81},{t:this.shape_80}]},1).to({state:[{t:this.shape_83},{t:this.shape_82}]},1).to({state:[{t:this.shape_85},{t:this.shape_84}]},1).to({state:[{t:this.shape_87},{t:this.shape_86}]},1).to({state:[{t:this.shape_89},{t:this.shape_88}]},1).to({state:[{t:this.shape_91},{t:this.shape_90}]},1).to({state:[{t:this.shape_93},{t:this.shape_92}]},1).to({state:[{t:this.shape_95},{t:this.shape_94}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-566.7,134.2,1045.2,387.40000000000003);


(lib.paperPlane_flying = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.paperPlane();
	this.instance.setTransform(-112.95,279.05,1,1,0,0,0,-106,71);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:-137.8,regY:63,rotation:0.1337,x:-142.3,y:269.35},0).wait(1).to({rotation:0.5486,x:-134.9,y:264.15},0).wait(1).to({rotation:1.2317,x:-122.3,y:255.6},0).wait(1).to({rotation:2.1639,x:-104.35,y:243.75},0).wait(1).to({rotation:3.3275,x:-80.7,y:228.85},0).wait(1).to({rotation:4.6898,x:-51.15,y:211.1},0).wait(1).to({rotation:6.2285,x:-14.95,y:190.65},0).wait(1).to({rotation:7.9095,x:28.15,y:167.95},0).wait(1).to({rotation:9.7061,x:78.7,y:143.25},0).wait(1).to({rotation:11.5912,x:137.35,y:117.05},0).wait(1).to({rotation:13.5385,x:204.45,y:89.8},0).wait(1).to({rotation:15.5356,x:280.75,y:61.9},0).wait(1).to({rotation:17.5628,x:366.4,y:33.95},0).wait(1).to({rotation:19.6152,x:462,y:6.7},0).wait(1).to({rotation:21.6907,x:567.8,y:-19.4},0).wait(1).to({rotation:23.7922,x:683.95,y:-43.55},0).wait(1).to({rotation:25.9325,x:810.35,y:-64.95},0).wait(1).to({rotation:28.1262,x:946.65,y:-82.7},0).wait(1).to({rotation:30.4012,x:1092.6,y:-95.95},0).wait(1).to({rotation:32.7933,x:1247.4,y:-103.65},0).wait(1).to({rotation:35.3501,x:1409.9,y:-104.7},0).wait(1).to({rotation:38.1396,x:1578.7,y:-98.05},0).wait(1).to({rotation:41.2484,x:1751.85,y:-82.35},0).wait(1).to({rotation:44.8048,x:1927.3,y:-56.25},0).wait(1).to({rotation:48.9824,x:2101.9,y:-18.4},0).wait(1).to({rotation:54.0331,x:2272.6,y:32.8},0).wait(1).to({rotation:60.3127,x:2435.45,y:99.25},0).wait(1).to({x:2576.4,y:180.4},0).wait(6).to({_off:true},1).wait(13));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-222.9,-136.9,2925.3,488.9);


// stage content:
(lib.ramirez_background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// leaves_foreground
	this.instance = new lib.tree_leaves_foreground();
	this.instance.setTransform(1033,54.2,1.3684,1.3684,0,0,0,-23.9,75.6);

	this.instance_1 = new lib.tree_leaves_foreground();
	this.instance_1.setTransform(190.95,207.1,1.104,1.104,0,0,0,-24,75.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

	// trees_foreground
	this.instance_2 = new lib.tree_trunk_foreground();
	this.instance_2.setTransform(187,413.6,1.5629,1.5629,0,0,0,0,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// leaf
	this.instance_3 = new lib.leaf();
	this.instance_3.setTransform(535.45,76.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// stairs
	this.stairs = new lib.stairs();
	this.stairs.name = "stairs";
	this.stairs.setTransform(536.65,484.35,1.3841,1.3841);

	this.timeline.addTween(cjs.Tween.get(this.stairs).wait(1));

	// plane
	this.instance_4 = new lib.paperPlane_flying();
	this.instance_4.setTransform(-48.1,403.75,0.3889,0.3889,0,0,0,-112.9,279);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// leaves_background
	this.instance_5 = new lib.tree_leaves_background();
	this.instance_5.setTransform(88.5,474.45,0.4056,0.5197,0,0,0,-23.8,75.6);

	this.instance_6 = new lib.tree_leaves_background();
	this.instance_6.setTransform(666.5,242.7,0.8179,0.8179,0,0,0,-24,75.6);

	this.instance_7 = new lib.tree_leaves_background();
	this.instance_7.setTransform(843.65,452.15,0.6343,0.5456,0,0,0,-23.9,75.6);

	this.instance_8 = new lib.tree_leaves_background();
	this.instance_8.setTransform(394.05,372.05,0.6342,0.6342,0,0,0,-23.9,75.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5}]}).wait(1));

	// trees_background
	this.instance_9 = new lib.tree_trunk_background();
	this.instance_9.setTransform(660,497.35,0.946,0.946);

	this.instance_10 = new lib.tree_trunk_background();
	this.instance_10.setTransform(396,550.85,0.7838,0.7838);

	this.instance_11 = new lib.tree_trunk_background();
	this.instance_11.setTransform(840,541.65,0.6748,0.6748);

	this.trunk = new lib.tree_trunk_background();
	this.trunk.name = "trunk";
	this.trunk.setTransform(88.55,571.75,0.595,0.595,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.trunk},{t:this.instance_11},{t:this.instance_10},{t:this.instance_9}]}).wait(1));

	// far_background
	this.instance_12 = new lib.tree_leaves_far_background();
	this.instance_12.setTransform(813.95,550.45,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_13 = new lib.tree_leaves_far_background();
	this.instance_13.setTransform(712.45,565.6,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_14 = new lib.tree_leaves_far_background();
	this.instance_14.setTransform(763.75,582.6,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_15 = new lib.tree_leaves_far_background();
	this.instance_15.setTransform(846.05,601.15,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_16 = new lib.tree_leaves_far_background();
	this.instance_16.setTransform(913,565.6,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_17 = new lib.tree_leaves_far_background();
	this.instance_17.setTransform(1000,572.15,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_18 = new lib.tree_leaves_far_background();
	this.instance_18.setTransform(958,594.6,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_19 = new lib.tree_leaves_far_background();
	this.instance_19.setTransform(455.85,557,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_20 = new lib.tree_leaves_far_background();
	this.instance_20.setTransform(354.35,572.15,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_21 = new lib.tree_leaves_far_background();
	this.instance_21.setTransform(405.65,589.15,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_22 = new lib.tree_leaves_far_background();
	this.instance_22.setTransform(487.95,607.7,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_23 = new lib.tree_leaves_far_background();
	this.instance_23.setTransform(554.9,572.15,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_24 = new lib.tree_leaves_far_background();
	this.instance_24.setTransform(641.9,578.7,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_25 = new lib.tree_leaves_far_background();
	this.instance_25.setTransform(599.9,601.15,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_26 = new lib.tree_leaves_far_background();
	this.instance_26.setTransform(117,540.05,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_27 = new lib.tree_leaves_far_background();
	this.instance_27.setTransform(15.5,555.2,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_28 = new lib.tree_leaves_far_background();
	this.instance_28.setTransform(66.8,572.2,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_29 = new lib.tree_leaves_far_background();
	this.instance_29.setTransform(149.1,590.75,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_30 = new lib.tree_leaves_far_background();
	this.instance_30.setTransform(216.05,555.2,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_31 = new lib.tree_leaves_far_background();
	this.instance_31.setTransform(303.05,561.75,0.3393,0.3393,0,0,0,-24,75.6);

	this.instance_32 = new lib.tree_leaves_far_background();
	this.instance_32.setTransform(261.05,584.2,0.3393,0.3393,0,0,0,-24,75.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_32},{t:this.instance_31},{t:this.instance_30},{t:this.instance_29},{t:this.instance_28},{t:this.instance_27},{t:this.instance_26},{t:this.instance_25},{t:this.instance_24},{t:this.instance_23},{t:this.instance_22},{t:this.instance_21},{t:this.instance_20},{t:this.instance_19},{t:this.instance_18},{t:this.instance_17},{t:this.instance_16},{t:this.instance_15},{t:this.instance_14},{t:this.instance_13},{t:this.instance_12}]}).wait(1));

	// sky
	this.instance_33 = new lib.sky();
	this.instance_33.setTransform(483.85,321.2,1.0742,2.2697,-90,0,0,6.5,5.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_33).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(389.1,56.4,915.1999999999999,631.7);
// library properties:
lib.properties = {
	id: '13A2A915B098454CBC613E0F0C1582F0',
	width: 960,
	height: 640,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['13A2A915B098454CBC613E0F0C1582F0'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;